; POKéMON
DEF _PIKACHU     EQU $0019 ; PIKACHU
DEF _RAICHU      EQU $001A ; RAICHU
DEF _SABELETTE   EQU $001B ; SABELETTE
DEF _SABLAIREAU  EQU $001C ; SABLAIREAU
DEF _GOUPIX      EQU $0025 ; GOUPIX
DEF _FEUNARD     EQU $0026 ; FEUNARD
DEF _RONDOUDOU   EQU $0027 ; RONDOUDOU
DEF _GRODOUDOU   EQU $0028 ; GRODOUDOU
DEF _NOSFERAPTI  EQU $0029 ; NOSFERAPTI
DEF _NOSFERALTO  EQU $002A ; NOSFERALTO
DEF _MYSTHERBE   EQU $002B ; MYSTHERBE
DEF _ORTIDE      EQU $002C ; ORTIDE
DEF _RAFFLESIA   EQU $002D ; RAFFLESIA
DEF _PSYKOKWAK   EQU $0036 ; PSYKOKWAK
DEF _AKWAKWAK    EQU $0037 ; AKWAKWAK
DEF _ABRA        EQU $003F ; ABRA
DEF _KADABRA     EQU $0040 ; KADABRA
DEF _ALAKAZAM    EQU $0041 ; ALAKAZAM
DEF _MACHOC      EQU $0042 ; MACHOC
DEF _MACHOPEUR   EQU $0043 ; MACHOPEUR
DEF _MACKOGNEUR  EQU $0044 ; MACKOGNEUR
DEF _TENTACOOL   EQU $0048 ; TENTACOOL
DEF _TENTACRUEL  EQU $0049 ; TENTACRUEL
DEF _RACAILLOU   EQU $004A ; RACAILLOU
DEF _GRAVALANCH  EQU $004B ; GRAVALANCH
DEF _GROLEM      EQU $004C ; GROLEM
DEF _MAGNETI     EQU $0051 ; MAGNETI
DEF _MAGNETON    EQU $0052 ; MAGNETON
DEF _DODUO       EQU $0054 ; DODUO
DEF _DODRIO      EQU $0055 ; DODRIO
DEF _TADMORV     EQU $0058 ; TADMORV
DEF _GROTADMORV  EQU $0059 ; GROTADMORV
DEF _VOLTORBE    EQU $0064 ; VOLTORBE
DEF _ELECTRODE   EQU $0065 ; ELECTRODE
DEF _SMOGO       EQU $006D ; SMOGO
DEF _SMOGOGO     EQU $006E ; SMOGOGO
DEF _RHINOCORNE  EQU $006F ; RHINOCORNE
DEF _RHINOFEROS  EQU $0070 ; RHINOFEROS
DEF _HYPOTREMPE  EQU $0074 ; HYPOTREMPE
DEF _HYPOCEAN    EQU $0075 ; HYPOCEAN
DEF _POISSIRENE  EQU $0076 ; POISSIRENE
DEF _POISSOROY   EQU $0077 ; POISSOROY
DEF _STARI       EQU $0078 ; STARI
DEF _STAROSS     EQU $0079 ; STAROSS
DEF _SCARABRUTE  EQU $007F ; SCARABRUTE
DEF _MAGICARPE   EQU $0081 ; MAGICARPE
DEF _LEVIATOR    EQU $0082 ; LEVIATOR
DEF _NOSTENFER   EQU $00A9 ; NOSTENFER
DEF _LOUPIO      EQU $00AA ; LOUPIO
DEF _LANTURN     EQU $00AB ; LANTURN
DEF _PICHU       EQU $00AC ; PICHU
DEF _TOUDOUDOU   EQU $00AE ; TOUDOUDOU
DEF _NATU        EQU $00B1 ; NATU
DEF _XATU        EQU $00B2 ; XATU
DEF _JOLIFLOR    EQU $00B6 ; JOLIFLOR
DEF _MARILL      EQU $00B7 ; MARILL
DEF _AZUMARILL   EQU $00B8 ; AZUMARILL
DEF _QULBUTOKE   EQU $00CA ; QULBUTOKE
DEF _GIRAFARIG   EQU $00CB ; GIRAFARIG
DEF _SCARHINO    EQU $00D6 ; SCARHINO
DEF _LIMAGMA     EQU $00DA ; LIMAGMA
DEF _VOLCAROPOD  EQU $00DB ; VOLCAROPOD
DEF _CORAYON     EQU $00DE ; CORAYON
DEF _AIRMURE     EQU $00E3 ; AIRMURE
DEF _HYPOROI     EQU $00E6 ; HYPOROI
DEF _PHANPY      EQU $00E7 ; PHANPY
DEF _DONPHAN     EQU $00E8 ; DONPHAN
DEF _ARCKO       EQU $0115 ; ARCKO
DEF _MASSKO      EQU $0116 ; MASSKO
DEF _JUNGKO      EQU $0117 ; JUNGKO
DEF _POUSSIFEU   EQU $0118 ; POUSSIFEU
DEF _GALIFEU     EQU $0119 ; GALIFEU
DEF _BRASEGALI   EQU $011A ; BRASEGALI
DEF _GOBOU       EQU $011B ; GOBOU
DEF _FLOBIO      EQU $011C ; FLOBIO
DEF _LAGGRON     EQU $011D ; LAGGRON
DEF _MEDHYENA    EQU $011E ; MEDHYENA
DEF _GRAHYENA    EQU $011F ; GRAHYENA
DEF _ZIGZATON    EQU $0120 ; ZIGZATON
DEF _LINEON      EQU $0121 ; LINEON
DEF _CHENIPOTTE  EQU $0122 ; CHENIPOTTE
DEF _ARMULYS     EQU $0123 ; ARMULYS
DEF _CHARMILLON  EQU $0124 ; CHARMILLON
DEF _BLINDALYS   EQU $0125 ; BLINDALYS
DEF _PAPINOX     EQU $0126 ; PAPINOX
DEF _NENUPIOT    EQU $0127 ; NENUPIOT
DEF _LOMBRE      EQU $0128 ; LOMBRE
DEF _LUDICOLO    EQU $0129 ; LUDICOLO
DEF _GRAINIPIOT  EQU $012A ; GRAINIPIOT
DEF _PIFEUIL     EQU $012B ; PIFEUIL
DEF _TENGALICE   EQU $012C ; TENGALICE
DEF _NINGALE     EQU $012D ; NINGALE
DEF _NINJASK     EQU $012E ; NINJASK
DEF _MUNJA       EQU $012F ; MUNJA
DEF _NIRONDELLE  EQU $0130 ; NIRONDELLE
DEF _HELEDELLE   EQU $0131 ; HELEDELLE
DEF _BALIGNON    EQU $0132 ; BALIGNON
DEF _CHAPIGNON   EQU $0133 ; CHAPIGNON
DEF _SPINDA      EQU $0134 ; SPINDA
DEF _GOELISE     EQU $0135 ; GOELISE
DEF _BEKIPAN     EQU $0136 ; BEKIPAN
DEF _ARAKDO      EQU $0137 ; ARAKDO
DEF _MASKADRA    EQU $0138 ; MASKADRA
DEF _WAILMER     EQU $0139 ; WAILMER
DEF _WAILORD     EQU $013A ; WAILORD
DEF _SKITTY      EQU $013B ; SKITTY
DEF _DELCATTY    EQU $013C ; DELCATTY
DEF _KECLEON     EQU $013D ; KECLEON
DEF _BALBUTO     EQU $013E ; BALBUTO
DEF _KAORINE     EQU $013F ; KAORINE
DEF _TARINOR     EQU $0140 ; TARINOR
DEF _CHARTOR     EQU $0141 ; CHARTOR
DEF _TENEFIX     EQU $0142 ; TENEFIX
DEF _BARLOCHE    EQU $0143 ; BARLOCHE
DEF _BARBICHA    EQU $0144 ; BARBICHA
DEF _LOVDISC     EQU $0145 ; LOVDISC
DEF _ECRAPINCE   EQU $0146 ; ECRAPINCE
DEF _COLHOMARD   EQU $0147 ; COLHOMARD
DEF _BARPAU      EQU $0148 ; BARPAU
DEF _MILOBELLUS  EQU $0149 ; MILOBELLUS
DEF _CARVANHA    EQU $014A ; CARVANHA
DEF _SHARPEDO    EQU $014B ; SHARPEDO
DEF _KRAKNOIX    EQU $014C ; KRAKNOIX
DEF _VIBRANINF   EQU $014D ; VIBRANINF
DEF _LIBEGON     EQU $014E ; LIBEGON
DEF _MAKUHITA    EQU $014F ; MAKUHITA
DEF _HARIYAMA    EQU $0150 ; HARIYAMA
DEF _DYNAVOLT    EQU $0151 ; DYNAVOLT
DEF _ELECSPRINT  EQU $0152 ; ELECSPRINT
DEF _CHAMALLOT   EQU $0153 ; CHAMALLOT
DEF _CAMERUPT    EQU $0154 ; CAMERUPT
DEF _OBALIE      EQU $0155 ; OBALIE
DEF _PHOGLEUR    EQU $0156 ; PHOGLEUR
DEF _KAIMORSE    EQU $0157 ; KAIMORSE
DEF _CACNEA      EQU $0158 ; CACNEA
DEF _CACTURNE    EQU $0159 ; CACTURNE
DEF _STALGAMIN   EQU $015A ; STALGAMIN
DEF _ONIGLALI    EQU $015B ; ONIGLALI
DEF _SELEROC     EQU $015C ; SELEROC
DEF _SOLAROC     EQU $015D ; SOLAROC
DEF _AZURILL     EQU $015E ; AZURILL
DEF _SPOINK      EQU $015F ; SPOINK
DEF _GRORET      EQU $0160 ; GRORET
DEF _POSIPI      EQU $0161 ; POSIPI
DEF _NEGAPI      EQU $0162 ; NEGAPI
DEF _MYSDIBULE   EQU $0163 ; MYSDIBULE
DEF _MEDITIKKA   EQU $0164 ; MEDITIKKA
DEF _CHARMINA    EQU $0165 ; CHARMINA
DEF _TYLTON      EQU $0166 ; TYLTON
DEF _ALTARIA     EQU $0167 ; ALTARIA
DEF _OKEOKE      EQU $0168 ; OKEOKE
DEF _SKELENOX    EQU $0169 ; SKELENOX
DEF _TERACLOPE   EQU $016A ; TERACLOPE
DEF _ROSELIA     EQU $016B ; ROSELIA
DEF _PARECOOL    EQU $016C ; PARECOOL
DEF _VIGOROTH    EQU $016D ; VIGOROTH
DEF _MONAFLEMIT  EQU $016E ; MONAFLEMIT
DEF _GLOUPTI     EQU $016F ; GLOUPTI
DEF _AVALTOUT    EQU $0170 ; AVALTOUT
DEF _TROPIUS     EQU $0171 ; TROPIUS
DEF _CHUCHMUR    EQU $0172 ; CHUCHMUR
DEF _RAMBOUM     EQU $0173 ; RAMBOUM
DEF _BROUHABAM   EQU $0174 ; BROUHABAM
DEF _COQUIPERL   EQU $0175 ; COQUIPERL
DEF _SERPANG     EQU $0176 ; SERPANG
DEF _ROSABYSS    EQU $0177 ; ROSABYSS
DEF _ABSOL       EQU $0178 ; ABSOL
DEF _POLICHOMBR  EQU $0179 ; POLICHOMBR
DEF _BRANETTE    EQU $017A ; BRANETTE
DEF _SEVIPER     EQU $017B ; SEVIPER
DEF _MANGRIFF    EQU $017C ; MANGRIFF
DEF _RELICANTH   EQU $017D ; RELICANTH
DEF _GALEKID     EQU $017E ; GALEKID
DEF _GALEGON     EQU $017F ; GALEGON
DEF _GALEKING    EQU $0180 ; GALEKING
DEF _MORPHEO     EQU $0181 ; MORPHEO
DEF _MUCIOLE     EQU $0182 ; MUCIOLE
DEF _LUMIVOLE    EQU $0183 ; LUMIVOLE
DEF _LILIA       EQU $0184 ; LILIA
DEF _VACILYS     EQU $0185 ; VACILYS
DEF _ANORITH     EQU $0186 ; ANORITH
DEF _ARMALDO     EQU $0187 ; ARMALDO
DEF _TARSAL      EQU $0188 ; TARSAL
DEF _KIRLIA      EQU $0189 ; KIRLIA
DEF _GARDEVOIR   EQU $018A ; GARDEVOIR
DEF _DRABY       EQU $018B ; DRABY
DEF _DRACKHAUS   EQU $018C ; DRACKHAUS
DEF _DRATTAK     EQU $018D ; DRATTAK
DEF _TERHAL      EQU $018E ; TERHAL
DEF _METANG      EQU $018F ; METANG
DEF _METALOSSE   EQU $0190 ; METALOSSE
DEF _REGIROCK    EQU $0191 ; REGIROCK
DEF _REGICE      EQU $0192 ; REGICE
DEF _REGISTEEL   EQU $0193 ; REGISTEEL
DEF _KYOGRE      EQU $0194 ; KYOGRE
DEF _GROUDON     EQU $0195 ; GROUDON
DEF _RAYQUAZA    EQU $0196 ; RAYQUAZA
DEF _LATIAS      EQU $0197 ; LATIAS
DEF _LATIOS      EQU $0198 ; LATIOS
DEF _JIRACHI     EQU $0199 ; JIRACHI
DEF _DEOXYS      EQU $019A ; DEOXYS
DEF _EOKO        EQU $019B ; EOKO

; DRESSEUR
DEF CE_SERA_TOI  EQU $0200 ; CE SERA TOI
DEF JE_T_AI_EU   EQU $0201 ; JE T’AI EU
DEF ECHANGER     EQU $0202 ; ECHANGER
DEF _SAPHIR      EQU $0203 ; SAPHIR
DEF EVOLUER      EQU $0204 ; EVOLUER
DEF ENCYCLOPEDIE EQU $0205 ; ENCYCLOPEDIE
DEF NATURE       EQU $0206 ; NATURE
DEF CENTRE       EQU $0207 ; CENTRE
DEF OEUF         EQU $0208 ; OEUF
DEF CONNEXION    EQU $0209 ; CONNEXION
DEF CAP__SPE_    EQU $020A ; CAP. SPE.
DEF DRESSEUR     EQU $020B ; DRESSEUR
DEF VERSION      EQU $020C ; VERSION
DEF POKENAV      EQU $020D ; POKéNAV
DEF POKEMON      EQU $020E ; POKéMON
DEF OBTENIR      EQU $020F ; OBTENIR
DEF POKEDEX      EQU $0210 ; POKéDEX
DEF _RUBIS       EQU $0211 ; RUBIS
DEF NIVEAU       EQU $0212 ; NIVEAU

; STATUT
DEF PSY          EQU $0400 ; PSY
DEF PUANTEUR     EQU $0401 ; PUANTEUR
DEF ISOGRAISSE   EQU $0402 ; ISOGRAISSE
DEF CUVETTE      EQU $0403 ; CUVETTE
DEF CRACHIN      EQU $0404 ; CRACHIN
DEF PIEGE        EQU $0405 ; PIEGE
DEF INTIMIDATION_ EQU $0406 ; INTIMIDATION
DEF TETE_DE_ROC  EQU $0407 ; TETE DE ROC
DEF COULEUR      EQU $0408 ; COULEUR
DEF MODIFICATION EQU $0409 ; MODIFICATION
DEF ROCHE        EQU $040A ; ROCHE
DEF MAGNIFIQUE   EQU $040B ; MAGNIFIQUE
DEF _BEAUTE      EQU $040C ; BEAUTE
DEF AIR_LOCK     EQU $040D ; AIR LOCK
DEF HORRIBLE     EQU $040E ; HORRIBLE
DEF HYPER_CUTTER EQU $040F ; HYPER CUTTER
DEF COMBAT       EQU $0410 ; COMBAT
DEF MARQUE_OMBRE EQU $0411 ; MARQUE OMBRE
DEF INTELLIGENT  EQU $0412 ; INTELLIGENT
DEF INTELLIGENCE EQU $0413 ; INTELLIGENCE
DEF TURBO        EQU $0414 ; TURBO
DEF COOL         EQU $0415 ; COOL
DEF SANG_FROID   EQU $0416 ; SANG-FROID
DEF ARMURBASTON  EQU $0417 ; ARMURBASTON
DEF GRACIEUX     EQU $0418 ; GRACIEUX
DEF GRACE        EQU $0419 ; GRACE
DEF FERMETE      EQU $041A ; FERMETE
DEF VENTOUSE     EQU $041B ; VENTOUSE
DEF PLANTE       EQU $041C ; PLANTE
DEF CORPS_SAIN   EQU $041D ; CORPS SAIN
DEF TORRENT      EQU $041E ; TORRENT
DEF SPECTRE      EQU $041F ; SPECTRE
DEF GLACE        EQU $0420 ; GLACE
DEF CRAN         EQU $0421 ; CRAN
DEF PEAU_DURE    EQU $0422 ; PEAU DURE
DEF COQUE_ARMURE EQU $0423 ; COQUE ARMURE
DEF MEDIC_NATURE EQU $0424 ; MEDIC NATURE
DEF MOITEUR      EQU $0425 ; MOITEUR
DEF SOL          EQU $0426 ; SOL
DEF ECHAUFFEMENT EQU $0427 ; ECHAUFFEMENT
DEF MAGNEPIEGE   EQU $0428 ; MAGNEPIEGE
DEF ECRAN_FUMEE  EQU $0429 ; ECRAN FUMEE
DEF SYNCHRO      EQU $042A ; SYNCHRO
DEF ENGRAIS      EQU $042B ; ENGRAIS
DEF GLISSADE     EQU $042C ; GLISSADE
DEF SABLE_VOLANT EQU $042D ; SABLE VOLANT
DEF VOILE_SABLE  EQU $042E ; VOILE SABLE
DEF REGARD_VIF   EQU $042F ; REGARD VIF
DEF OBJECTIF     EQU $0430 ; OBJECTIF
DEF STATIK       EQU $0431 ; STATIK
DEF TYPE         EQU $0432 ; TYPE
DEF CORIACE      EQU $0433 ; CORIACE
DEF ROBUSTESSE   EQU $0434 ; ROBUSTESSE
DEF MUE          EQU $0435 ; MUE
DEF COLOFORCE    EQU $0436 ; COLOFORCE
DEF ABSORB_VOLT  EQU $0437 ; ABSORB VOLT
DEF ABSORB_EAU   EQU $0438 ; ABSORB EAU
DEF ELECTRIK     EQU $0439 ; ELECTRIK
DEF METEO        EQU $043A ; METEO
DEF SERENITE     EQU $043B ; SERENITE
DEF POISON       EQU $043C ; POISON
DEF POINT_POISON EQU $043D ; POINT POISON
DEF DRAGON       EQU $043E ; DRAGON
DEF CALQUE       EQU $043F ; CALQUE
DEF BENET        EQU $0440 ; BENET
DEF ABSENTEISME  EQU $0441 ; ABSENTEISME
DEF FUITE        EQU $0442 ; FUITE
DEF GLUE         EQU $0443 ; GLUE
DEF CIEL_GRIS    EQU $0444 ; CIEL GRIS
DEF NORMAL       EQU $0445 ; NORMAL
DEF ACIER        EQU $0446 ; ACIER
DEF LUMIATIRANCE EQU $0447 ; LUMIATIRANCE
DEF MATINAL      EQU $0448 ; MATINAL
DEF AGITATION    EQU $0449 ; AGITATION
DEF SOLEIL       EQU $044A ; SOLEIL
DEF VOL_          EQU $044B ; VOL
DEF SECHERESSE   EQU $044C ; SECHERESSE
DEF PARATONNERRE EQU $044D ; PARATONNERRE
DEF OEIL_COMPOSE EQU $044E ; OEIL COMPOSE
DEF ECAILLE_SPE_ EQU $044F ; ECAILLE SPE.
DEF GARDE_MYSTIK EQU $0450 ; GARDE MYSTIK
DEF INSOMNIA     EQU $0451 ; INSOMNIA
DEF LEVITATION   EQU $0452 ; LEVITATION
DEF PLUS         EQU $0453 ; PLUS
DEF PRESSION     EQU $0454 ; PRESSION
DEF SUINTEMENT   EQU $0455 ; SUINTEMENT
DEF DEGUISEMENT  EQU $0456 ; DEGUISEMENT
DEF ANTI_BRUIT   EQU $0457 ; ANTI-BRUIT
DEF POSE_SPORE   EQU $0458 ; POSE SPORE
DEF POKERUS      EQU $0459 ; POKéRUS
DEF FEU          EQU $045A ; FEU
DEF CORPS_ARDENT EQU $045B ; CORPS ARDENT
DEF MINUS        EQU $045C ; MINUS
DEF TEMPO_PERSO  EQU $045D ; TEMPO PERSO
DEF ARMUMAGMA    EQU $045E ; ARMUMAGMA
DEF EAU          EQU $045F ; EAU
DEF IGNIFU_VOILE EQU $0460 ; IGNIFU-VOILE
DEF INSECTE      EQU $0461 ; INSECTE
DEF ESSAIM       EQU $0462 ; ESSAIM
DEF JOLI_SOURIRE EQU $0463 ; JOLI SOURIRE
DEF VACCIN       EQU $0464 ; VACCIN
DEF BRASIER      EQU $0465 ; BRASIER
DEF RAMASSAGE    EQU $0466 ; RAMASSAGE
DEF SCHEMA       EQU $0467 ; SCHEMA
DEF TORCHE       EQU $0468 ; TORCHE
DEF ESPRIT_VITAL EQU $0469 ; ESPRIT VITAL
DEF CHLOROPHYLE  EQU $046A ; CHLOROPHYLE
DEF FORCE_PURE   EQU $046B ; FORCE PURE
DEF ECRAN_POUDRE EQU $046C ; ECRAN POUDRE

; COMBAT
DEF TECHNIQUE    EQU $0600 ; TECHNIQUE
DEF ALLEZ        EQU $0601 ; ALLEZ
DEF N__1         EQU $0602 ; Nº 1
DEF DECIDER      EQU $0603 ; DECIDER
DEF TENACITE_     EQU $0604 ; TENACITE
DEF GAGNE        EQU $0605 ; GAGNE
DEF GAGNER       EQU $0606 ; GAGNER
DEF REUSSITE     EQU $0607 ; REUSSITE
DEF SI_JE_GAGNE  EQU $0608 ; SI JE GAGNE
DEF BATTRE       EQU $0609 ; BATTRE
DEF ECHEC        EQU $060A ; ECHEC
DEF INTIMIDANT   EQU $060B ; INTIMIDANT
DEF TROP_NUL     EQU $060C ; TROP NUL
DEF ESPRIT       EQU $060D ; ESPRIT
DEF DEMENAGER    EQU $060E ; DEMENAGER
DEF AVANTAGE     EQU $060F ; AVANTAGE
DEF PRENDS_CA_   EQU $0610 ; PRENDS CA!
DEF ASSURER      EQU $0611 ; ASSURER
DEF ATTAQUER     EQU $0612 ; ATTAQUER
DEF SE_RENDRE    EQU $0613 ; SE RENDRE
DEF COURAGE      EQU $0614 ; COURAGE
DEF TALENT       EQU $0615 ; TALENT
DEF STRATEGIE    EQU $0616 ; STRATEGIE
DEF VIOLENCE     EQU $0617 ; VIOLENCE
DEF MATCH        EQU $0618 ; MATCH
DEF VICTOIRE     EQU $0619 ; VICTOIRE
DEF FUIR         EQU $061A ; FUIR
DEF SENS         EQU $061B ; SENS
DEF CONTRE_       EQU $061C ; CONTRE
DEF DISPUTE      EQU $061D ; DISPUTE
DEF PUISSANT     EQU $061E ; PUISSANT
DEF DEFI         EQU $061F ; DEFI
DEF FORT         EQU $0620 ; FORT
DEF TROP_FORT    EQU $0621 ; TROP FORT
DEF TRANQUILLE   EQU $0622 ; TRANQUILLE
DEF ENNEMI       EQU $0623 ; ENNEMI
DEF GENIE        EQU $0624 ; GENIE
DEF LEGENDE      EQU $0625 ; LEGENDE
DEF ECHAPPER     EQU $0626 ; ECHAPPER
DEF BUT          EQU $0627 ; BUT
DEF LUTTE_        EQU $0628 ; LUTTE
DEF COMBATTRE    EQU $0629 ; COMBATTRE
DEF RESSUSCITER  EQU $062A ; RESSUSCITER
DEF POINTS       EQU $062B ; POINTS
DEF SERIEUX      EQU $062C ; SERIEUX
DEF ABANDONNER   EQU $062D ; ABANDONNER
DEF DEFAITE      EQU $062E ; DEFAITE
DEF SI_JE_PERDS  EQU $062F ; SI JE PERDS
DEF PERDU        EQU $0630 ; PERDU
DEF PERDRE       EQU $0631 ; PERDRE
DEF VIGILANCE    EQU $0632 ; VIGILANCE
DEF PARTENAIRE   EQU $0633 ; PARTENAIRE
DEF REFUSER      EQU $0634 ; REFUSER
DEF ACCEPTER     EQU $0635 ; ACCEPTER
DEF INVINCIBLE   EQU $0636 ; INVINCIBLE
DEF RECU         EQU $0637 ; RECU
DEF FACILE       EQU $0638 ; FACILE
DEF FAIBLE       EQU $0639 ; FAIBLE
DEF TROP_FAIBLE  EQU $063A ; TROP FAIBLE
DEF NULLITE      EQU $063B ; NULLITE
DEF _LEADER      EQU $063C ; LEADER
DEF VIVE         EQU $063D ; VIVE
DEF CAPACITE     EQU $063E ; CAPACITE

; «POLITESSES»
DEF MERCI_BIEN_  EQU $0800 ; MERCI BIEN!
DEF OUI          EQU $0801 ; OUI
DEF DEBUTONS     EQU $0802 ; DEBUTONS
DEF ME_VOILA     EQU $0803 ; ME VOILA
DEF VOICI        EQU $0804 ; VOICI
DEF OUAIS        EQU $0805 ; OUAIS
DEF BIENVENUE    EQU $0806 ; BIENVENUE
DEF CA_VA_       EQU $0807 ; CA VA?
DEF SECOUE_MOI   EQU $0808 ; SECOUE-MOI
DEF FELICITATION EQU $0809 ; FELICITATION
DEF DONNE_MOI    EQU $080A ; DONNE-MOI
DEF EXCUSE_MOI   EQU $080B ; EXCUSE-MOI
DEF ATTENTION    EQU $080C ; ATTENTION
DEF PARDON       EQU $080D ; PARDON
DEF HE_TOI_      EQU $080E ; HE TOI!
DEF SALUT        EQU $080F ; SALUT
DEF AU_REVOIR    EQU $0810 ; AU REVOIR
DEF MERCI        EQU $0811 ; MERCI
DEF JE_SUIS_LA   EQU $0812 ; JE SUIS LA
DEF C_EST_PARTI  EQU $0813 ; C’EST PARTI
DEF BIEN         EQU $0814 ; BIEN
DEF A_PLUS       EQU $0815 ; A PLUS
DEF MONTRE_MOI   EQU $0816 ; MONTRE-MOI
DEF HE_BIEN      EQU $0817 ; HE BIEN
DEF VAS_Y        EQU $0818 ; VAS-Y
DEF QUELLE_JOIE  EQU $0819 ; QUELLE JOIE
DEF JE_VOIS      EQU $081A ; JE VOIS
DEF CA_VA_BIEN_  EQU $081B ; CA VA BIEN?
DEF HEIN_        EQU $081C ; HEIN?
DEF NON          EQU $081D ; NON
DEF COUCOU       EQU $081E ; COUCOU
DEF OUAIS_OUAIS  EQU $081F ; OUAIS OUAIS
DEF CIAO_        EQU $0820 ; CIAO!
DEF ENCHANTE     EQU $0821 ; ENCHANTE
DEF HE           EQU $0822 ; HE
DEF BONJOUR      EQU $0823 ; BONJOUR
DEF A_PLUS_      EQU $0824 ; A PLUS!
DEF WOO_AH       EQU $0825 ; WOO-AH
DEF HOUHOU       EQU $0826 ; HOUHOU
DEF YO           EQU $0827 ; YO
DEF VIENS_LA     EQU $0828 ; VIENS-LA
DEF C_EST_CA     EQU $0829 ; C’EST CA

; PERSONNES
DEF ADVERSAIRE   EQU $0A00 ; ADVERSAIRE
DEF JE           EQU $0A01 ; JE
DEF TU           EQU $0A02 ; TU
DEF TON          EQU $0A03 ; TON
DEF FILS         EQU $0A04 ; FILS
DEF TES          EQU $0A05 ; TES
DEF TU_ES        EQU $0A06 ; TU ES
DEF TU_AS        EQU $0A07 ; TU AS
DEF MERE         EQU $0A08 ; MERE
DEF GRAND_PERE   EQU $0A09 ; GRAND-PERE
DEF ONCLE        EQU $0A0A ; ONCLE
DEF PERE         EQU $0A0B ; PERE
DEF GARCON       EQU $0A0C ; GARCON
DEF ADULTE       EQU $0A0D ; ADULTE
DEF FRERE        EQU $0A0E ; FRERE
DEF SOEUR        EQU $0A0F ; SŒUR
DEF GRAND_MERE   EQU $0A10 ; GRAND-MERE
DEF TANTE        EQU $0A11 ; TANTE
DEF PARENTS      EQU $0A12 ; PARENTS
DEF HOMME        EQU $0A13 ; HOMME
DEF MOI          EQU $0A14 ; MOI
DEF FILLE        EQU $0A15 ; FILLE
DEF BEBE         EQU $0A16 ; BEBE
DEF FAMILLE      EQU $0A17 ; FAMILLE
DEF TA           EQU $0A18 ; TA
DEF TOI          EQU $0A19 ; TOI
DEF IL           EQU $0A1A ; IL
DEF IL_A         EQU $0A1B ; IL A
DEF MA           EQU $0A1C ; MA
DEF SES          EQU $0A1D ; SES
DEF IL_EST       EQU $0A1E ; IL EST
DEF SE           EQU $0A1F ; SE
DEF TE           EQU $0A20 ; TE
DEF GOSSE        EQU $0A21 ; GOSSE
DEF ENFANTS      EQU $0A22 ; ENFANTS
DEF MONSIEUR     EQU $0A23 ; MONSIEUR
DEF MADAME       EQU $0A24 ; MADAME
DEF LEURS        EQU $0A25 ; LEURS
DEF J_ETAIS      EQU $0A26 ; J’ETAIS
DEF ON_A         EQU $0A27 ; ON A
DEF MON          EQU $0A28 ; MON
DEF JE_SUIS      EQU $0A29 ; JE SUIS
DEF J_AI         EQU $0A2A ; J’AI
DEF QUI          EQU $0A2B ; QUI
DEF J_           EQU $0A2C ; J’
DEF ME           EQU $0A2D ; ME
DEF ON_EST       EQU $0A2E ; ON EST
DEF ELLES        EQU $0A2F ; ELLES
DEF MES          EQU $0A30 ; MES
DEF C_EST        EQU $0A31 ; C’EST
DEF _JEUNE_FILLE EQU $0A32 ; JEUNE FILLE
DEF AMIS         EQU $0A33 ; AMIS
DEF ALLIE        EQU $0A34 ; ALLIE
DEF PERSONNE     EQU $0A35 ; PERSONNE
DEF MEC          EQU $0A36 ; MEC
DEF ILS          EQU $0A37 ; ILS
DEF ILS_ETAIENT  EQU $0A38 ; ILS ETAIENT
DEF NOS          EQU $0A39 ; NOS
DEF LEUR         EQU $0A3A ; LEUR
DEF ILS_SONT     EQU $0A3B ; ILS SONT
DEF ILS_ONT      EQU $0A3C ; ILS ONT
DEF NOUS         EQU $0A3D ; NOUS
DEF SON          EQU $0A3E ; SON
DEF ON           EQU $0A3F ; ON
DEF NOTRE        EQU $0A40 ; NOTRE
DEF NOUS_VOULONS EQU $0A41 ; NOUS VOULONS
DEF JEUNE        EQU $0A42 ; JEUNE
DEF NOUS_AVONS   EQU $0A43 ; NOUS AVONS
DEF FEMME        EQU $0A44 ; FEMME
DEF ELLE         EQU $0A45 ; ELLE
DEF ELLE_ETAIT   EQU $0A46 ; ELLE ETAIT
DEF ELLE_A       EQU $0A47 ; ELLE A
DEF SA           EQU $0A48 ; SA
DEF ELLE_EST     EQU $0A49 ; ELLE EST
DEF CERTAINS     EQU $0A4A ; CERTAINS

; REACTIONS
DEF __EX         EQU $0C00 ; !
DEF __EX_EX      EQU $0C01 ; !!
DEF __QU_EX      EQU $0C02 ; ?!
DEF __QU         EQU $0C03 ; ?
DEF __ELIP       EQU $0C04 ; ...
DEF __ELIP_EX    EQU $0C05 ; ...!
DEF __ELIP3      EQU $0C06 ; .........
DEF __HYPHEN     EQU $0C07 ; -
DEF __HYPHEN3    EQU $0C08 ; - - -
DEF HUM_HUM      EQU $0C09 ; HUM HUM
DEF OUAH         EQU $0C0A ; OUAH
DEF HA__HA__HA_  EQU $0C0B ; HA! HA! HA!
DEF HO_          EQU $0C0C ; HO?
DEF NAN          EQU $0C0D ; NAN
DEF URGH         EQU $0C0E ; URGH
DEF HUMMM        EQU $0C0F ; HUMMM
DEF WAOUH        EQU $0C10 ; WAOUH
DEF AHHHHH_      EQU $0C11 ; AHHHHH!
DEF WOUUUU_      EQU $0C12 ; WOUUUU!
DEF GLOUSSEMENT  EQU $0C13 ; GLOUSSEMENT
DEF SNIFF        EQU $0C14 ; SNIFF
DEF INCROYABLE   EQU $0C15 ; INCROYABLE
DEF PLEURS       EQU $0C16 ; PLEURS
DEF D_ACCORD     EQU $0C17 ; D’ACCORD
DEF QUOI_        EQU $0C18 ; QUOI?
DEF CRI          EQU $0C19 ; CRI
DEF HE__HE__HE_  EQU $0C1A ; HE! HE! HE!
DEF AIE_AIE_AIE  EQU $0C1B ; AIE AIE AIE
DEF AH_OUI       EQU $0C1C ; AH OUI
DEF OH           EQU $0C1D ; OH
DEF OUPS         EQU $0C1E ; OUPS
DEF HO_LA_LA     EQU $0C1F ; HO LA LA
DEF OUILLE       EQU $0C20 ; OUILLE
DEF GRAAA_       EQU $0C21 ; GRAAA!
DEF CRRRRR       EQU $0C22 ; CRRRRR
DEF COOL___      EQU $0C23 ; COOL!!!
DEF PSHT         EQU $0C24 ; PSHT
DEF HE__HE_      EQU $0C25 ; HE! HE!
DEF HA_          EQU $0C26 ; HA!
DEF YOUPI        EQU $0C27 ; YOUPI
DEF BEURK        EQU $0C28 ; BEURK
DEF YOUHOU_      EQU $0C29 ; YOUHOU!
DEF OUAIP        EQU $0C2A ; OUAIP
DEF HOUHOUHOU    EQU $0C2B ; HOUHOUHOU
DEF HI__HI__HI_  EQU $0C2C ; HI! HI! HI!
DEF RRRH         EQU $0C2D ; RRRH
DEF HOURRA       EQU $0C2E ; HOURRA
DEF VLAN         EQU $0C2F ; VLAN
DEF HEEEE        EQU $0C30 ; HEEEE
DEF HO_HO_HO     EQU $0C31 ; HO HO HO
DEF HA           EQU $0C32 ; HA
DEF DIS_DONC     EQU $0C33 ; DIS DONC
DEF ARRRG        EQU $0C34 ; ARRRG
DEF HO           EQU $0C35 ; HO
DEF MMM          EQU $0C36 ; MMM
DEF MOUAIS       EQU $0C37 ; MOUAIS
DEF OK           EQU $0C38 ; OK
DEF LA_LA_LA     EQU $0C39 ; LA LA LA
DEF YESSS        EQU $0C3A ; YESSS
DEF HEP          EQU $0C3B ; HEP
DEF WOUHOU       EQU $0C3C ; WOUHOU
DEF OUIN         EQU $0C3D ; OUIN
DEF OUAHAHA      EQU $0C3E ; OUAHAHA

; DISCOURS
DEF QUELQU_UN    EQU $0E00 ; QUELQU’UN
DEF PAS_TROP     EQU $0E01 ; PAS TROP
DEF DESAGREABLE  EQU $0E02 ; DESAGREABLE
DEF TOUT_A_FAIT  EQU $0E03 ; TOUT A FAIT
DEF ENCORE_       EQU $0E04 ; ENCORE
DEF TROP         EQU $0E05 ; TROP
DEF BOF          EQU $0E06 ; BOF
DEF PLUTOT       EQU $0E07 ; PLUTOT
DEF A_PARTIR_DE  EQU $0E08 ; A PARTIR DE
DEF LA           EQU $0E09 ; LA
DEF MAIS         EQU $0E0A ; MAIS
DEF CEPENDANT    EQU $0E0B ; CEPENDANT
DEF LES          EQU $0E0C ; LES
DEF LE           EQU $0E0D ; LE
DEF L_           EQU $0E0E ; L’
DEF COMMENT      EQU $0E0F ; COMMENT
DEF SUCCES       EQU $0E10 ; SUCCES
DEF SUFFIT       EQU $0E11 ; SUFFIT
DEF BEAUCOUP     EQU $0E12 ; BEAUCOUP
DEF UN_PEU       EQU $0E13 ; UN PEU
DEF ABSOLUMENT   EQU $0E14 ; ABSOLUMENT
DEF _ET          EQU $0E15 ; ET
DEF SEULEMENT    EQU $0E16 ; SEULEMENT
DEF AUTOUR       EQU $0E17 ; AUTOUR
DEF SUREMENT     EQU $0E18 ; SUREMENT
DEF CA           EQU $0E19 ; CA
DEF TRES         EQU $0E1A ; TRES
DEF JUSTE_UN_PEU EQU $0E1B ; JUSTE UN PEU
DEF SAUVAGE      EQU $0E1C ; SAUVAGE
DEF AU           EQU $0E1D ; AU
DEF JUSTE        EQU $0E1E ; JUSTE
DEF _A           EQU $0E1F ; A
DEF EN_FAIT      EQU $0E20 ; EN FAIT
DEF BIEN_SUR     EQU $0E21 ; BIEN SUR
DEF C_EST_SUR    EQU $0E22 ; C’EST SUR
DEF COMPRIS      EQU $0E23 ; COMPRIS
DEF POUR_RIRE    EQU $0E24 ; POUR RIRE
DEF PRET         EQU $0E25 ; PRET
DEF QUELQUE      EQU $0E26 ; QUELQUE
DEF A_PEU_PRES   EQU $0E27 ; A PEU PRES
DEF BIEN_QUE     EQU $0E28 ; BIEN QUE
DEF AUSSI        EQU $0E29 ; AUSSI
DEF PARFAIT      EQU $0E2A ; PARFAIT
DEF AUTANT_QUE   EQU $0E2B ; AUTANT QUE
DEF VRAIMENT     EQU $0E2C ; VRAIMENT
DEF REELLEMENT   EQU $0E2D ; REELLEMENT
DEF SERIEUSEMENT EQU $0E2E ; SERIEUSEMENT
DEF COMPLETEMENT EQU $0E2F ; COMPLETEMENT
DEF JUSQUE       EQU $0E30 ; JUSQUE
DEF COMME_SI     EQU $0E31 ; COMME SI
DEF DES          EQU $0E32 ; DES
DEF TELLEMENT    EQU $0E33 ; TELLEMENT
DEF TERRIBLEMENT EQU $0E34 ; TERRIBLEMENT
DEF MOINS        EQU $0E35 ; MOINS
DEF DAVANTAGE    EQU $0E36 ; DAVANTAGE
DEF TROP_TARD    EQU $0E37 ; TROP TARD
DEF FINALEMENT   EQU $0E38 ; FINALEMENT
DEF PEU_IMPORTE  EQU $0E39 ; PEU IMPORTE
DEF AU_LIEU_DE   EQU $0E3A ; AU LIEU DE
DEF FANTASTIQUE  EQU $0E3B ; FANTASTIQUE

; LIAISON
DEF JE_VAIS      EQU $1000 ; JE VAIS
DEF DU           EQU $1001 ; DU
DEF _OU          EQU $1002 ; OU
DEF FOIS         EQU $1003 ; FOIS
DEF D_           EQU $1004 ; D’
DEF D_ACCORD_    EQU $1005 ; D’ACCORD?
DEF ETRE         EQU $1006 ; ETRE
DEF D_UN         EQU $1007 ; D’UN
DEF PEUX         EQU $1008 ; PEUX
DEF TU_VAS       EQU $1009 ; TU VAS
DEF TU_SEMBLES   EQU $100A ; TU SEMBLES
DEF EST          EQU $100B ; EST
DEF NON_         EQU $100C ; NON?
DEF SOIS         EQU $100D ; SOIS
DEF AUTRE        EQU $100E ; AUTRE
DEF SONT         EQU $100F ; SONT
DEF ETAIT        EQU $1010 ; ETAIT
DEF ETAIS        EQU $1011 ; ETAIS
DEF CEUX         EQU $1012 ; CEUX
DEF NE           EQU $1013 ; NE
DEF FERA         EQU $1014 ; FERA
DEF IL_Y_A       EQU $1015 ; IL Y A
DEF JE_PEUX      EQU $1016 ; JE PEUX
DEF JE_DOIS      EQU $1017 ; JE DOIS
DEF JE_PERDS     EQU $1018 ; JE PERDS
DEF ES_TU        EQU $1019 ; ES-TU
DEF AS_TU        EQU $101A ; AS-TU
DEF LEQUEL       EQU $101B ; LEQUEL
DEF LAQUELLE     EQU $101C ; LAQUELLE
DEF LESQUELS     EQU $101D ; LESQUELS
DEF AVOIR        EQU $101E ; AVOIR
DEF LESQUELLES   EQU $101F ; LESQUELLES
DEF UN           EQU $1020 ; UN
DEF UNE          EQU $1021 ; UNE
DEF PAS          EQU $1022 ; PAS
DEF ICI          EQU $1023 ; ICI
DEF OK_          EQU $1024 ; OK?
DEF _SI          EQU $1025 ; SI
DEF PEUT_ETRE    EQU $1026 ; PEUT-ETRE
DEF FAISANT      EQU $1027 ; FAISANT
DEF APPRENDS     EQU $1028 ; APPRENDS
DEF TU_VEUX      EQU $1029 ; TU VEUX
DEF TOUT         EQU $102A ; TOUT
DEF POUR         EQU $102B ; POUR
DEF VEUX         EQU $102C ; VEUX
DEF VONT         EQU $102D ; VONT
DEF DONC         EQU $102E ; DONC
DEF TU_FAIS      EQU $102F ; TU FAIS
DEF AVEC         EQU $1030 ; AVEC
DEF MIEUX        EQU $1031 ; MIEUX
DEF AIME         EQU $1032 ; AIME
DEF DEPUIS       EQU $1033 ; DEPUIS
DEF _DE          EQU $1034 ; DE
DEF VA           EQU $1035 ; VA
DEF LA_BAS       EQU $1036 ; LA-BAS
DEF EN           EQU $1037 ; EN
DEF DEHORS       EQU $1038 ; DEHORS
DEF PAREIL       EQU $1039 ; PAREIL
DEF J_AIME       EQU $103A ; J’AIME
DEF IL_FAUT      EQU $103B ; IL FAUT
DEF FAIS         EQU $103C ; FAIS
DEF FAUT_PAS     EQU $103D ; FAUT PAS
DEF SANS         EQU $103E ; SANS
DEF DANS         EQU $103F ; DANS
DEF C_EST_VRAI   EQU $1040 ; C’EST VRAI
DEF DURANT       EQU $1041 ; DURANT
DEF ONT          EQU $1042 ; ONT
DEF UNE_FOIS     EQU $1043 ; UNE FOIS
DEF PARTOUT      EQU $1044 ; PARTOUT

; EMOTIONS
DEF JOYEUX       EQU $1200 ; JOYEUX
DEF SATISFAIT    EQU $1201 ; SATISFAIT
DEF PRESSE       EQU $1202 ; PRESSE
DEF INSATISFAIT  EQU $1203 ; INSATISFAIT
DEF ETOURDI      EQU $1204 ; ETOURDI
DEF HEUREUX      EQU $1205 ; HEUREUX
DEF BONHEUR      EQU $1206 ; BONHEUR
DEF ENERVE       EQU $1207 ; ENERVE
DEF IMPRESSIONNE EQU $1208 ; IMPRESSIONNE
DEF DROLE        EQU $1209 ; DROLE
DEF HUMEUR       EQU $120A ; HUMEUR
DEF DEMORALISE   EQU $120B ; DEMORALISE
DEF DECU         EQU $120C ; DECU
DEF RAVI         EQU $120D ; RAVI
DEF TRISTE       EQU $120E ; TRISTE
DEF CONTENT      EQU $120F ; CONTENT
DEF MECONTENT    EQU $1210 ; MECONTENT
DEF DEGOUTE      EQU $1211 ; DEGOUTE
DEF ECOEURE      EQU $1212 ; ECŒURE
DEF RASSURE      EQU $1213 ; RASSURE
DEF EFFRAYE      EQU $1214 ; EFFRAYE
DEF PASSIONNE    EQU $1215 ; PASSIONNE
DEF ACHARNE      EQU $1216 ; ACHARNE
DEF EN_COLERE    EQU $1217 ; EN COLERE
DEF COLERE_       EQU $1218 ; COLERE
DEF EFFRAYANT    EQU $1219 ; EFFRAYANT
DEF SOLITUDE     EQU $121A ; SOLITUDE
DEF FURIEUX      EQU $121B ; FURIEUX
DEF JOIE         EQU $121C ; JOIE
DEF MOTIVE       EQU $121D ; MOTIVE
DEF SOUCIEUX     EQU $121E ; SOUCIEUX
DEF ZUT          EQU $121F ; ZUT
DEF DECOURAGE    EQU $1220 ; DECOURAGE
DEF MERVEILLEUX  EQU $1221 ; MERVEILLEUX
DEF INQUIET      EQU $1222 ; INQUIET
DEF IMPATIENT    EQU $1223 ; IMPATIENT
DEF ENNUYEUX     EQU $1224 ; ENNUYEUX
DEF CONFIANT     EQU $1225 ; CONFIANT
DEF SURPRIS      EQU $1226 ; SURPRIS
DEF ETONNE       EQU $1227 ; ETONNE
DEF J_ADORE      EQU $1228 ; J’ADORE
DEF DESASTRE     EQU $1229 ; DESASTRE
DEF STRESSE      EQU $122A ; STRESSE
DEF NERVEUX      EQU $122B ; NERVEUX
DEF HUMILIE      EQU $122C ; HUMILIE
DEF FIER         EQU $122D ; FIER
DEF MAUVAIS      EQU $122E ; MAUVAIS
DEF DIFFICILE    EQU $122F ; DIFFICILE
DEF ATROCE       EQU $1230 ; ATROCE
DEF DEVRAIT      EQU $1231 ; DEVRAIT
DEF SYMPA        EQU $1232 ; SYMPA
DEF HONTEUX      EQU $1233 ; HONTEUX
DEF SURPRISE     EQU $1234 ; SURPRISE
DEF PEUR         EQU $1235 ; PEUR
DEF JE_VEUX      EQU $1236 ; JE VEUX
DEF ANXIEUX      EQU $1237 ; ANXIEUX
DEF REJOUI       EQU $1238 ; REJOUI
DEF VOIR         EQU $1239 ; VOIR
DEF RARE         EQU $123A ; RARE
DEF NEGATIF      EQU $123B ; NEGATIF
DEF FURAX        EQU $123C ; FURAX
DEF DANGER       EQU $123D ; DANGER
DEF BATTU        EQU $123E ; BATTU
DEF EMERVEILLE   EQU $123F ; EMERVEILLE
DEF SPLENDIDE    EQU $1240 ; SPLENDIDE
DEF ROMANTIQUE   EQU $1241 ; ROMANTIQUE
DEF QUESTION     EQU $1242 ; QUESTION
DEF COMPRENDS    EQU $1243 ; COMPRENDS
DEF COMPREND     EQU $1244 ; COMPREND

; ETAT
DEF CHAUD        EQU $1400 ; CHAUD
DEF EXISTE       EQU $1401 ; EXISTE
DEF EXCES        EQU $1402 ; EXCES
DEF APPROUVE     EQU $1403 ; APPROUVE
DEF LENT         EQU $1404 ; LENT
DEF BON          EQU $1405 ; BON
DEF LENTEUR      EQU $1406 ; LENTEUR
DEF VITESSE      EQU $1407 ; VITESSE
DEF FACILITE     EQU $1408 ; FACILITE
DEF BIZARRE      EQU $1409 ; BIZARRE
DEF OCCUPE       EQU $140A ; OCCUPE
DEF ENSEMBLE     EQU $140B ; ENSEMBLE
DEF PLEIN        EQU $140C ; PLEIN
DEF ABSENT       EQU $140D ; ABSENT
DEF ETANT        EQU $140E ; ETANT
DEF J_AI_BESOIN  EQU $140F ; J’AI BESOIN
DEF DELICIEUX    EQU $1410 ; DELICIEUX
DEF DOUE         EQU $1411 ; DOUE
DEF BRUYANT      EQU $1412 ; BRUYANT
DEF ENORME       EQU $1413 ; ENORME
DEF TARD         EQU $1414 ; TARD
DEF PROCHE       EQU $1415 ; PROCHE
DEF DOCILE       EQU $1416 ; DOCILE
DEF AMUSANT      EQU $1417 ; AMUSANT
DEF DISTRAYANT   EQU $1418 ; DISTRAYANT
DEF PERFECTION   EQU $1419 ; PERFECTION
DEF JOLI         EQU $141A ; JOLI
DEF EN_FORME     EQU $141B ; EN FORME
DEF REMARQUABLE  EQU $141C ; REMARQUABLE
DEF BEBETE       EQU $141D ; BEBETE
DEF FROID        EQU $141E ; FROID
DEF FRAIS        EQU $141F ; FRAIS
DEF INEVITABLE   EQU $1420 ; INEVITABLE
DEF IGNORANT     EQU $1421 ; IGNORANT
DEF IRRESISTIBLE EQU $1422 ; IRRESISTIBLE
DEF FABULEUX     EQU $1423 ; FABULEUX
DEF NUNUCHE      EQU $1424 ; NUNUCHE
DEF CHER         EQU $1425 ; CHER
DEF CORRECTEMENT EQU $1426 ; CORRECTEMENT
DEF IMPOSSIBLE   EQU $1427 ; IMPOSSIBLE
DEF PETIT        EQU $1428 ; PETIT
DEF DIFFERENT    EQU $1429 ; DIFFERENT
DEF FATIGUE      EQU $142A ; FATIGUE
DEF HABILETE     EQU $142B ; HABILETE
DEF MAXIMUM      EQU $142C ; MAXIMUM
DEF NON_STOP     EQU $142D ; NON-STOP
DEF RIDICULE     EQU $142E ; RIDICULE
DEF AUCUN        EQU $142F ; AUCUN
DEF RIEN         EQU $1430 ; RIEN
DEF NATUREL      EQU $1431 ; NATUREL
DEF DEVIENT      EQU $1432 ; DEVIENT
DEF TIEDE        EQU $1433 ; TIEDE
DEF RAPIDE       EQU $1434 ; RAPIDE
DEF BAS          EQU $1435 ; BAS
DEF TERRIBLE     EQU $1436 ; TERRIBLE
DEF SEUL         EQU $1437 ; SEUL
DEF JE_M_ENNUIE  EQU $1438 ; JE M’ENNUIE
DEF SECRET       EQU $1439 ; SECRET
DEF MYSTERE      EQU $143A ; MYSTERE
DEF IL_MANQUE    EQU $143B ; IL MANQUE
DEF MEILLEUR     EQU $143C ; MEILLEUR
DEF MINABLE      EQU $143D ; MINABLE
DEF ERREUR       EQU $143E ; ERREUR
DEF AGREABLE     EQU $143F ; AGREABLE
DEF PIRE         EQU $1440 ; PIRE
DEF AFFAIBLI     EQU $1441 ; AFFAIBLI
DEF SIMPLE       EQU $1442 ; SIMPLE
DEF ON_DIRAIT    EQU $1443 ; ON DIRAIT
DEF GRAVEMENT    EQU $1444 ; GRAVEMENT

; ACTIONS
DEF RENCONTRER   EQU $1600 ; RENCONTRER
DEF CEDE         EQU $1601 ; CEDE
DEF DONNER       EQU $1602 ; DONNER
DEF DONNE        EQU $1603 ; DONNE
DEF JOUER        EQU $1604 ; JOUER
DEF JOUE         EQU $1605 ; JOUE
DEF COLLECTIONNE EQU $1606 ; COLLECTIONNE
DEF MARCHER      EQU $1607 ; MARCHER
DEF MARCHE       EQU $1608 ; MARCHE
DEF DIS          EQU $1609 ; DIS
DEF ALLE         EQU $160A ; ALLE
DEF DIT          EQU $160B ; DIT
DEF REVEILLE_TOI EQU $160C ; REVEILLE-TOI
DEF REVEILLE     EQU $160D ; REVEILLE
DEF ENERVER      EQU $160E ; ENERVER
DEF ENSEIGNER    EQU $160F ; ENSEIGNER
DEF ENSEIGNE     EQU $1610 ; ENSEIGNE
DEF S_TE_PLAIT   EQU $1611 ; S’TE PLAIT
DEF APPRENDRE    EQU $1612 ; APPRENDRE
DEF CHANGE       EQU $1613 ; CHANGE
DEF HISTOIRE     EQU $1614 ; HISTOIRE
DEF CONFIANCE    EQU $1615 ; CONFIANCE
DEF DEPENSE      EQU $1616 ; DEPENSE
DEF ECOUTER      EQU $1617 ; ECOUTER
DEF ENTENDRE     EQU $1618 ; ENTENDRE
DEF ENTRAINE     EQU $1619 ; ENTRAINE
DEF CHOISIS      EQU $161A ; CHOISIS
DEF VIENS        EQU $161B ; VIENS
DEF VENU         EQU $161C ; VENU
DEF RECHERCHE    EQU $161D ; RECHERCHE
DEF FAIRE        EQU $161E ; FAIRE
DEF PROVOQUE     EQU $161F ; PROVOQUE
DEF CONNAIT      EQU $1620 ; CONNAIT
DEF CONNAIS      EQU $1621 ; CONNAIS
DEF REFUSE       EQU $1622 ; REFUSE
DEF SURPRENDRE   EQU $1623 ; SURPRENDRE
DEF VANTE        EQU $1624 ; VANTE
DEF CASSE        EQU $1625 ; CASSE
DEF PENSE        EQU $1626 ; PENSE
DEF CROIRE       EQU $1627 ; CROIRE
DEF GLISSE       EQU $1628 ; GLISSE
DEF MANGE        EQU $1629 ; MANGE
DEF UTILISE      EQU $162A ; UTILISE
DEF UTILISER     EQU $162B ; UTILISER
DEF EN_UTILISANT EQU $162C ; EN UTILISANT
DEF REGARDER     EQU $162D ; REGARDER
DEF CAPABLE      EQU $162E ; CAPABLE
DEF DISPARAITRE  EQU $162F ; DISPARAITRE
DEF APPARAIS     EQU $1630 ; APPARAIS
DEF LANCE        EQU $1631 ; LANCE
DEF COURIR       EQU $1632 ; COURIR
DEF DORMI        EQU $1633 ; DORMI
DEF DORMIR       EQU $1634 ; DORMIR
DEF LIBERE       EQU $1635 ; LIBERE
DEF BOIT         EQU $1636 ; BOIT
DEF COURT        EQU $1637 ; COURT
DEF JE_COURS     EQU $1638 ; JE COURS
DEF TRAVAILLE    EQU $1639 ; TRAVAILLE
DEF TRAVAILLER   EQU $163A ; TRAVAILLER
DEF PARLER       EQU $163B ; PARLER
DEF PARLE        EQU $163C ; PARLE
DEF COULE        EQU $163D ; COULE
DEF TAPE         EQU $163E ; TAPE
DEF PRETENDS     EQU $163F ; PRETENDS
DEF LOUE         EQU $1640 ; LOUE
DEF EXAGERE      EQU $1641 ; EXAGERE
DEF MONTRER      EQU $1642 ; MONTRER
DEF REGARDE      EQU $1643 ; REGARDE
DEF VOIT         EQU $1644 ; VOIT
DEF CHERCHE      EQU $1645 ; CHERCHE
DEF ECOUTE       EQU $1646 ; ECOUTE
DEF PRENDS       EQU $1647 ; PRENDS
DEF PERMETS      EQU $1648 ; PERMETS
DEF OUBLIE       EQU $1649 ; OUBLIE
DEF OUBLIER      EQU $164A ; OUBLIER
DEF APPARAIT     EQU $164B ; APPARAIT
DEF EVANOUIS     EQU $164C ; EVANOUIS
DEF EVANOUI      EQU $164D ; EVANOUI

; VIE QUOTIDIEN.
DEF ROUTINE      EQU $1800 ; ROUTINE
DEF MAISON       EQU $1801 ; MAISON
DEF ARGENT       EQU $1802 ; ARGENT
DEF TRANSPORTS   EQU $1803 ; TRANSPORTS
DEF BAIN         EQU $1804 ; BAIN
DEF CONVERSATION EQU $1805 ; CONVERSATION
DEF ECOLE        EQU $1806 ; ECOLE
DEF ANNIVERSAIRE EQU $1807 ; ANNIVERSAIRE
DEF HABITUDES    EQU $1808 ; HABITUDES
DEF GROUPE       EQU $1809 ; GROUPE
DEF MOT          EQU $180A ; MOT
DEF MAGASIN      EQU $180B ; MAGASIN
DEF SERVICE      EQU $180C ; SERVICE
DEF TRAVAIL      EQU $180D ; TRAVAIL
DEF SYSTEME      EQU $180E ; SYSTEME
DEF TRAIN        EQU $180F ; TRAIN
DEF CLASSE       EQU $1810 ; CLASSE
DEF DEVOIRS      EQU $1811 ; DEVOIRS
DEF INFORMATIONS EQU $1812 ; INFORMATIONS
DEF QUOTIDIEN    EQU $1813 ; QUOTIDIEN
DEF PROFESSEUR   EQU $1814 ; PROFESSEUR
DEF TOURNOI      EQU $1815 ; TOURNOI
DEF LETTRE       EQU $1816 ; LETTRE
DEF EVENEMENT    EQU $1817 ; EVENEMENT
DEF NUMERIQUE    EQU $1818 ; NUMERIQUE
DEF CONTROLE     EQU $1819 ; CONTROLE
DEF EPICERIE     EQU $181A ; EPICERIE
DEF TELEVISION   EQU $181B ; TELEVISION
DEF TELEPHONE    EQU $181C ; TELEPHONE
DEF OBJET        EQU $181D ; OBJET
DEF NOM          EQU $181E ; NOM
DEF NOUVELLES    EQU $181F ; NOUVELLES
DEF CELEBRE      EQU $1820 ; CELEBRE
DEF FETE         EQU $1821 ; FETE
DEF ETUDIER      EQU $1822 ; ETUDIER
DEF ORDINATEUR   EQU $1823 ; ORDINATEUR
DEF COURRIER     EQU $1824 ; COURRIER
DEF MESSAGE      EQU $1825 ; MESSAGE
DEF PROMESSE     EQU $1826 ; PROMESSE
DEF REVE         EQU $1827 ; REVE
DEF MATERNELLE   EQU $1828 ; MATERNELLE
DEF VIE          EQU $1829 ; VIE
DEF RADIO        EQU $182A ; RADIO
DEF LOYER        EQU $182B ; LOYER
DEF MONDE        EQU $182C ; MONDE

; HOBBIES
DEF STAR         EQU $1A00 ; STAR
DEF DESSIN_ANIME EQU $1A01 ; DESSIN ANIME
DEF CHANSON      EQU $1A02 ; CHANSON
DEF CINEMA       EQU $1A03 ; CINEMA
DEF BONBONS      EQU $1A04 ; BONBONS
DEF DISCUTER     EQU $1A05 ; DISCUTER
DEF JEU_D_ENFANT EQU $1A06 ; JEU D’ENFANT
DEF JOUETS       EQU $1A07 ; JOUETS
DEF MUSIQUE      EQU $1A08 ; MUSIQUE
DEF CARTES       EQU $1A09 ; CARTES
DEF SHOPPING     EQU $1A0A ; SHOPPING
DEF PHOTOGRAPHIE EQU $1A0B ; PHOTOGRAPHIE
DEF FOYER        EQU $1A0C ; FOYER
DEF THEATRE      EQU $1A0D ; THEATRE
DEF CUISINE      EQU $1A0E ; CUISINE
DEF JEUX         EQU $1A0F ; JEUX
DEF JEUX_DE_ROLE EQU $1A10 ; JEUX DE ROLE
DEF COLLECTION   EQU $1A11 ; COLLECTION
DEF JEUX_VIDEO   EQU $1A12 ; JEUX VIDEO
DEF MAGAZINES    EQU $1A13 ; MAGAZINES
DEF COURSE       EQU $1A14 ; COURSE
DEF VELO         EQU $1A15 ; VELO
DEF HOBBY        EQU $1A16 ; HOBBY
DEF SPORT        EQU $1A17 ; SPORT
DEF LOGICIELS    EQU $1A18 ; LOGICIELS
DEF CHANTER      EQU $1A19 ; CHANTER
DEF DIETETIQUE   EQU $1A1A ; DIETETIQUE
DEF TRESORS      EQU $1A1B ; TRESORS
DEF VOYAGES      EQU $1A1C ; VOYAGES
DEF DANSE        EQU $1A1D ; DANSE
DEF CHAINE       EQU $1A1E ; CHAINE
DEF BRICOLAGE    EQU $1A1F ; BRICOLAGE
DEF PECHE        EQU $1A20 ; PECHE
DEF RENDEZ_VOUS  EQU $1A21 ; RENDEZ-VOUS
DEF DESSIN       EQU $1A22 ; DESSIN
DEF PETIT_TRAIN  EQU $1A23 ; PETIT TRAIN
DEF NOUNOURS     EQU $1A24 ; NOUNOURS
DEF INFORMATIQUE EQU $1A25 ; INFORMATIQUE
DEF JARDINAGE    EQU $1A26 ; JARDINAGE
DEF HEROS        EQU $1A27 ; HEROS
DEF SIESTE       EQU $1A28 ; SIESTE
DEF HEROINE      EQU $1A29 ; HEROINE
DEF MODE         EQU $1A2A ; MODE
DEF AVENTURE     EQU $1A2B ; AVENTURE
DEF BATEAU       EQU $1A2C ; BATEAU
DEF FOOTBALL     EQU $1A2D ; FOOTBALL
DEF LIVRE        EQU $1A2E ; LIVRE
DEF FESTIVALS    EQU $1A2F ; FESTIVALS
DEF BD           EQU $1A30 ; BD
DEF VACANCES     EQU $1A31 ; VACANCES
DEF LECTURE      EQU $1A32 ; LECTURE
DEF A_LA_MODE    EQU $1A33 ; A LA MODE
DEF TOURISME     EQU $1A34 ; TOURISME
DEF COCOONING    EQU $1A35 ; COCOONING

; TEMPORALITE
DEF AUTOMNE      EQU $1C00 ; AUTOMNE
DEF MATIN        EQU $1C01 ; MATIN
DEF DEMAIN       EQU $1C02 ; DEMAIN
DEF DERNIER      EQU $1C03 ; DERNIER
DEF JOUR         EQU $1C04 ; JOUR
DEF UN_JOUR      EQU $1C05 ; UN JOUR
DEF TOUJOURS     EQU $1C06 ; TOUJOURS
DEF ACTUELLEMENT EQU $1C07 ; ACTUELLEMENT
DEF APRES        EQU $1C08 ; APRES
DEF JOURS        EQU $1C09 ; JOURS
DEF FIN          EQU $1C0A ; FIN
DEF MARDI        EQU $1C0B ; MARDI
DEF HIER         EQU $1C0C ; HIER
DEF AUJOURD_HUI  EQU $1C0D ; AUJOURD’HUI
DEF VENDREDI     EQU $1C0E ; VENDREDI
DEF LUNDI        EQU $1C0F ; LUNDI
DEF PLUS_TARD    EQU $1C10 ; PLUS TARD
DEF PLUS_TOT     EQU $1C11 ; PLUS TOT
DEF TOUT_L_TEMPS EQU $1C12 ; TOUT L’TEMPS
DEF TEMPS        EQU $1C13 ; TEMPS
DEF TERMINER     EQU $1C14 ; TERMINER
DEF MERCREDI     EQU $1C15 ; MERCREDI
DEF BIENTOT      EQU $1C16 ; BIENTOT
DEF COMMENCER    EQU $1C17 ; COMMENCER
DEF MOIS         EQU $1C18 ; MOIS
DEF _STOP        EQU $1C19 ; STOP
DEF MAINTENANT   EQU $1C1A ; MAINTENANT
DEF FINAL        EQU $1C1B ; FINAL
DEF PROCHAIN     EQU $1C1C ; PROCHAIN
DEF AGE          EQU $1C1D ; AGE
DEF SAMEDI       EQU $1C1E ; SAMEDI
DEF ETE          EQU $1C1F ; ETE
DEF DIMANCHE     EQU $1C20 ; DIMANCHE
DEF DEBUT        EQU $1C21 ; DEBUT
DEF PRINTEMPS    EQU $1C22 ; PRINTEMPS
DEF JOURNEE      EQU $1C23 ; JOURNEE
DEF HIVER        EQU $1C24 ; HIVER
DEF LE_JOUR      EQU $1C25 ; LE JOUR
DEF AUTREFOIS    EQU $1C26 ; AUTREFOIS
DEF PRESQUE      EQU $1C27 ; PRESQUE
DEF PENDANT      EQU $1C28 ; PENDANT
DEF JEUDI        EQU $1C29 ; JEUDI
DEF AVANT        EQU $1C2A ; AVANT
DEF NUIT         EQU $1C2B ; NUIT
DEF SEMAINE      EQU $1C2C ; SEMAINE

; DIVERS
DEF HAUTEUR      EQU $1E00 ; HAUTEUR
DEF PROFONDEUR   EQU $1E01 ; PROFONDEUR
DEF FACON        EQU $1E02 ; FACON
DEF CHOC         EQU $1E03 ; CHOC
DEF CHOSES       EQU $1E04 ; CHOSES
DEF CHOSE        EQU $1E05 ; CHOSE
DEF EN_DESSOUS   EQU $1E06 ; EN DESSOUS
DEF AU_DESSUS    EQU $1E07 ; AU-DESSUS
DEF DERRIERE     EQU $1E08 ; DERRIERE
DEF HAUT         EQU $1E09 ; HAUT
DEF CES          EQU $1E0A ; CES
DEF DEDANS       EQU $1E0B ; DEDANS
DEF EXTERIEUR    EQU $1E0C ; EXTERIEUR
DEF BATS         EQU $1E0D ; BATS
DEF CETTE        EQU $1E0E ; CETTE
DEF CE           EQU $1E0F ; CE
DEF CHAQUE       EQU $1E10 ; CHAQUE
DEF DESTINEE     EQU $1E11 ; DESTINEE
DEF RENCONTRE    EQU $1E12 ; RENCONTRE
DEF ANTICIPATION EQU $1E13 ; ANTICIPATION
DEF QUE          EQU $1E14 ; QUE
DEF TOUR_DE      EQU $1E15 ; TOUR DE
DEF DESSUS       EQU $1E16 ; DESSUS
DEF CEUX_QUI     EQU $1E17 ; CEUX QUI
DEF PROPRE       EQU $1E18 ; PROPRE
DEF C_ETAIT      EQU $1E19 ; C’ETAIT
DEF DEVANT       EQU $1E1A ; DEVANT
DEF SUR          EQU $1E1B ; SUR
DEF CHOIX        EQU $1E1C ; CHOIX
DEF LOIN         EQU $1E1D ; LOIN
DEF ODEUR        EQU $1E1E ; ODEUR
DEF PRES         EQU $1E1F ; PRES
DEF QUELLE       EQU $1E20 ; QUELLE
DEF QUAND        EQU $1E21 ; QUAND
DEF QUEL         EQU $1E22 ; QUEL
DEF PROFOND      EQU $1E23 ; PROFOND
DEF SUPERFICIEL  EQU $1E24 ; SUPERFICIEL
DEF POURQUOI     EQU $1E25 ; POURQUOI
DEF CONFUS       EQU $1E26 ; CONFUS
DEF OPPOSE       EQU $1E27 ; OPPOSE
DEF GAUCHE       EQU $1E28 ; GAUCHE
DEF DROITE       EQU $1E29 ; DROITE

; QUALIFICATIFS
DEF NOMADE       EQU $2000 ; NOMADE
DEF MINUSCULE    EQU $2001 ; MINUSCULE
DEF SOLIDE       EQU $2002 ; SOLIDE
DEF FAIM         EQU $2003 ; FAIM
DEF SERRE        EQU $2004 ; SERRE
DEF CHATOUILLEUX EQU $2005 ; CHATOUILLEUX
DEF TORDU        EQU $2006 ; TORDU
DEF EN_SPIRALE   EQU $2007 ; EN SPIRALE
DEF SOIF         EQU $2008 ; SOIF
DEF INTERESSANT  EQU $2009 ; INTERESSANT
DEF SOYEUX       EQU $200A ; SOYEUX
DEF TRISTEMENT   EQU $200B ; TRISTEMENT
DEF SANS_ESPOIR  EQU $200C ; SANS ESPOIR
DEF SANS_INTERET EQU $200D ; SANS INTERET
DEF ADMIRATIF    EQU $200E ; ADMIRATIF
DEF PASSIONNANT  EQU $200F ; PASSIONNANT
DEF EPAIS        EQU $2010 ; EPAIS
DEF LISSE        EQU $2011 ; LISSE
DEF MINCE        EQU $2012 ; MINCE
DEF GRACIEUSE    EQU $2013 ; GRACIEUSE
DEF DECEVANT     EQU $2014 ; DECEVANT
DEF VORACEMENT   EQU $2015 ; VORACEMENT
DEF DISPERSE     EQU $2016 ; DISPERSE
DEF GENIAL       EQU $2017 ; GENIAL
DEF MAUVIETTE    EQU $2018 ; MAUVIETTE
DEF BANCAL       EQU $2019 ; BANCAL
DEF TREMBLANT    EQU $201A ; TREMBLANT
DEF DECHIRE      EQU $201B ; DECHIRE
DEF EN_LAMBEAUX  EQU $201C ; EN LAMBEAUX
DEF EN_HAUSSE    EQU $201D ; EN HAUSSE
DEF IMPORTANT    EQU $201E ; IMPORTANT
DEF DETRUIT      EQU $201F ; DETRUIT
DEF FOUGUEUX     EQU $2020 ; FOUGUEUX
DEF MIMI         EQU $2021 ; MIMI
DEF HEUREUSEMENT EQU $2022 ; HEUREUSEMENT
DEF ATTENDU      EQU $2023 ; ATTENDU

; EVENEMENTS
DEF CHARME_       EQU $2200 ; CHARME
DEF EVENEMENTS   EQU $2201 ; EVENEMENTS
DEF ARENE        EQU $2202 ; ARENE
DEF BAIE         EQU $2203 ; BAIE
DEF CONCOURS     EQU $2204 ; CONCOURS
DEF ANIMATRICE   EQU $2205 ; ANIMATRICE
DEF JUGE         EQU $2206 ; JUGE
DEF SUPER        EQU $2207 ; SUPER
DEF VILLE        EQU $2208 ; VILLE
DEF PANTHEON     EQU $2209 ; PANTHEON
DEF EVOLUTION    EQU $220A ; EVOLUTION
DEF HYPER        EQU $220B ; HYPER
DEF TOUR_COMBAT  EQU $220C ; TOUR COMBAT
DEF CHEFS        EQU $220D ; CHEFS
DEF SALLE_COMBAT EQU $220E ; SALLE COMBAT
DEF CACHE        EQU $220F ; CACHE
DEF BASE_SECRETE EQU $2210 ; BASE SECRETE
DEF MIXER        EQU $2211 ; MIXER
DEF POKEBLOC     EQU $2212 ; POKéBLOC
DEF MAITRE       EQU $2213 ; MAITRE
DEF CATEGORIE    EQU $2214 ; CATEGORIE
DEF RUBAN        EQU $2215 ; RUBAN

; CAPACITE 1
DEF _POING_KARATE EQU $2402 ; POING-KARATE
DEF _TORGNOLES   EQU $2403 ; TORGNOLES
DEF _POING_ECLAIR EQU $2409 ; POING-ECLAIR
DEF _COUPE_VENT  EQU $240D ; COUPE-VENT
DEF _COUPE       EQU $240F ; COUPE
DEF _TORNADE     EQU $2410 ; TORNADE
DEF _VOL         EQU $2413 ; VOL
DEF _ETREINTE    EQU $2414 ; ETREINTE
DEF _JET_DE_SABLE EQU $241C ; JET DE SABLE
DEF _COUP_D_BOULE EQU $241D ; COUP D’BOULE
DEF _MANIA       EQU $2425 ; MANIA
DEF _DAMOCLES    EQU $2426 ; DAMOCLES
DEF _MIMI_QUEUE  EQU $2427 ; MIMI-QUEUE
DEF _MORSURE     EQU $242C ; MORSURE
DEF _BERCEUSE    EQU $242F ; BERCEUSE
DEF _SONICBOOM   EQU $2431 ; SONICBOOM
DEF _ENTRAVE     EQU $2432 ; ENTRAVE
DEF _LANCE_FLAMME EQU $2435 ; LANCE-FLAMME
DEF _BRUME       EQU $2436 ; BRUME
DEF _RAFALE_PSY  EQU $243C ; RAFALE PSY
DEF _ONDE_BOREALE EQU $243E ; ONDE BOREALE
DEF _SACRIFICE   EQU $2442 ; SACRIFICE
DEF _BALAYAGE    EQU $2443 ; BALAYAGE
DEF _RIPOSTE     EQU $2444 ; RIPOSTE
DEF _FORCE       EQU $2446 ; FORCE
DEF _VOL_VIE     EQU $2447 ; VOL-VIE
DEF _CROISSANCE  EQU $244A ; CROISSANCE
DEF _LANCE_SOLEIL EQU $244C ; LANCE-SOLEIL
DEF _PARA_SPORE  EQU $244E ; PARA-SPORE
DEF _SECRETION   EQU $2451 ; SECRETION
DEF _TONNERRE    EQU $2455 ; TONNERRE
DEF _FATAL_FOUDRE EQU $2457 ; FATAL-FOUDRE
DEF _JET_PIERRES EQU $2458 ; JET-PIERRES
DEF _SEISME      EQU $2459 ; SEISME
DEF _ABIME       EQU $245A ; ABIME
DEF _TUNNEL      EQU $245B ; TUNNEL
DEF _PSYKO       EQU $245E ; PSYKO
DEF _HYPNOSE     EQU $245F ; HYPNOSE
DEF _HATE        EQU $2461 ; HATE
DEF _FRENESIE    EQU $2463 ; FRENESIE
DEF _GRINCEMENT  EQU $2467 ; GRINCEMENT
DEF _REFLET      EQU $2468 ; REFLET
DEF _SOIN        EQU $2469 ; SOIN
DEF _ARMURE      EQU $246A ; ARMURE
DEF _BROUILLARD  EQU $246C ; BROUILLARD
DEF _ONDE_FOLIE  EQU $246D ; ONDE FOLIE
DEF _REPLI       EQU $246E ; REPLI
DEF _BUEE_NOIRE  EQU $2472 ; BUEE NOIRE
DEF _PUISSANCE   EQU $2474 ; PUISSANCE
DEF _PATIENCE    EQU $2475 ; PATIENCE
DEF _MIMIQUE     EQU $2477 ; MIMIQUE
DEF _DESTRUCTION EQU $2478 ; DESTRUCTION
DEF _LECHOUILLE  EQU $247A ; LECHOUILLE
DEF _PUREDPOIS   EQU $247B ; PUREDPOIS
DEF _CLAQUOIR    EQU $2480 ; CLAQUOIR
DEF _METEORES    EQU $2481 ; METEORES
DEF _CONSTRICTION EQU $2484 ; CONSTRICTION
DEF _TELEKINESIE EQU $2486 ; TELEKINESIE
DEF _VAMPIRISME  EQU $248D ; VAMPIRISME
DEF _GROBISOU    EQU $248E ; GROBISOU
DEF _PIQUE       EQU $248F ; PIQUE
DEF _ECUME       EQU $2491 ; ECUME
DEF _SPORE       EQU $2493 ; SPORE
DEF _VAGUE_PSY   EQU $2495 ; VAGUE PSY
DEF _PINCE_MASSE EQU $2498 ; PINCE-MASSE
DEF _EBOULEMENT  EQU $249D ; EBOULEMENT
DEF _AFFUTAGE    EQU $249F ; AFFUTAGE
DEF _CROC_FATAL  EQU $24A2 ; CROC FATAL
DEF _TRANCHE     EQU $24A3 ; TRANCHE
DEF _GRIBOUILLE  EQU $24A6 ; GRIBOUILLE
DEF _TOILE       EQU $24A9 ; TOILE
DEF _LIRE_ESPRIT EQU $24AA ; LIRE-ESPRIT
DEF _CAUCHEMAR   EQU $24AB ; CAUCHEMAR
DEF _ROUE_DE_FEU EQU $24AC ; ROUE DE FEU
DEF _RONFLEMENT  EQU $24AD ; RONFLEMENT
DEF _FLEAU       EQU $24AF ; FLEAU
DEF _AEROBLAST   EQU $24B1 ; AEROBLAST
DEF _CONTRE      EQU $24B3 ; CONTRE
DEF _DEPIT       EQU $24B4 ; DEPIT
DEF _POUDREUSE   EQU $24B5 ; POUDREUSE
DEF _GRIMACE     EQU $24B8 ; GRIMACE
DEF _OCTAZOOKA   EQU $24BE ; OCTAZOOKA
DEF _VENT_GLACE  EQU $24C4 ; VENT GLACE
DEF _COLERE      EQU $24C8 ; COLERE
DEF _TEMPETESABLE EQU $24C9 ; TEMPETESABLE
DEF _GIGA_SANGSUE EQU $24CA ; GIGA-SANGSUE
DEF _TENACITE    EQU $24CB ; TENACITE
DEF _CHARME      EQU $24CC ; CHARME
DEF _ROULADE     EQU $24CD ; ROULADE
DEF _VANTARDISE  EQU $24CF ; VANTARDISE
DEF _ETINCELLE   EQU $24D1 ; ETINCELLE
DEF _REGARD_NOIR EQU $24D4 ; REGARD NOIR
DEF _GLAS_DE_SOIN EQU $24D7 ; GLAS DE SOIN
DEF _RETOUR      EQU $24D8 ; RETOUR
DEF _RUNE_PROTECT EQU $24DB ; RUNE PROTECT
DEF _BALANCE     EQU $24DC ; BALANCE
DEF _FEU_SACRE   EQU $24DD ; FEU SACRE
DEF _ENCORE      EQU $24E3 ; ENCORE
DEF _POURSUITE   EQU $24E4 ; POURSUITE
DEF _TOUR_RAPIDE EQU $24E5 ; TOUR RAPIDE
DEF _DOUX_PARFUM EQU $24E6 ; DOUX PARFUM
DEF _QUEUE_DE_FER EQU $24E7 ; QUEUE DE FER
DEF _CORPS_PERDU EQU $24E9 ; CORPS PERDU
DEF _AURORE      EQU $24EA ; AURORE
DEF _SYNTHESE    EQU $24EB ; SYNTHESE
DEF _COUP_CROIX  EQU $24EE ; COUP-CROIX
DEF _DANSE_PLUIE EQU $24F0 ; DANSE PLUIE
DEF _MACHOUILLE  EQU $24F2 ; MACHOUILLE
DEF _BOOST       EQU $24F4 ; BOOST
DEF _VIT_EXTREME EQU $24F5 ; VIT.EXTREME
DEF _POUV_ANTIQUE EQU $24F6 ; POUV.ANTIQUE
DEF _BALL_OMBRE  EQU $24F7 ; BALL’OMBRE
DEF _ECLATE_ROC  EQU $24F9 ; ECLATE-ROC
DEF _SIPHON      EQU $24FA ; SIPHON
DEF _BROUHAHA    EQU $24FD ; BROUHAHA
DEF _GRELE       EQU $2502 ; GRELE
DEF _TOURMENTE   EQU $2503 ; TOURMENTE
DEF _FLATTERIE   EQU $2504 ; FLATTERIE
DEF _FEU_FOLLET  EQU $2505 ; FEU FOLLET
DEF _SOUVENIR    EQU $2506 ; SOUVENIR
DEF _FACADE      EQU $2507 ; FACADE
DEF _MITRA_POING EQU $2508 ; MITRA-POING
DEF _STIMULANT   EQU $2509 ; STIMULANT
DEF _PAR_ICI     EQU $250A ; PAR ICI
DEF _FORCE_NATURE EQU $250B ; FORCE-NATURE
DEF _CHARGEUR    EQU $250C ; CHARGEUR
DEF _CASSE_BRIQUE EQU $2518 ; CASSE-BRIQUE
DEF _BAILLEMENT  EQU $2519 ; BAILLEMENT
DEF _EFFORT      EQU $251B ; EFFORT
DEF _ECHANGE     EQU $251D ; ECHANGE
DEF _RANCUNE     EQU $2520 ; RANCUNE
DEF _BALL_GLACE  EQU $252D ; BALL’GLACE
DEF _POING_METEOR EQU $2535 ; POING METEOR
DEF _ETONNEMENT  EQU $2536 ; ETONNEMENT
DEF _BALL_METEO  EQU $2537 ; BALL’METEO
DEF _AROMATHERAPI EQU $2538 ; AROMATHERAPI
DEF _CROCO_LARME EQU $2539 ; CROCO LARME
DEF _TRANCH_AIR  EQU $253A ; TRANCH’AIR
DEF _SURCHAUFFE  EQU $253B ; SURCHAUFFE
DEF _FLAIR       EQU $253C ; FLAIR
DEF _TOMBEROCHE  EQU $253D ; TOMBEROCHE
DEF _VENT_ARGENTE EQU $253E ; VENT ARGENTE
DEF _STRIDO_SON  EQU $253F ; STRIDO-SON
DEF _SIFFL_HERBE EQU $2540 ; SIFFL’HERBE
DEF _CHATOUILLE  EQU $2541 ; CHATOUILLE
DEF _FORCE_COSMIK EQU $2542 ; FORCE COSMIK
DEF _GICLEDO     EQU $2543 ; GICLEDO
DEF _RAYON_SIGNAL EQU $2544 ; RAYON SIGNAL
DEF _POING_OMBRE EQU $2545 ; POING OMBRE
DEF _EXTRASENSEUR EQU $2546 ; EXTRASENSEUR
DEF _STRATOPERCUT EQU $2547 ; STRATOPERCUT
DEF _TOURBI_SABLE EQU $2548 ; TOURBI-SABLE
DEF _GLACIATION  EQU $2549 ; GLACIATION

; CAPACITE 2
DEF _ECRAS_FACE  EQU $2601 ; ECRAS’FACE
DEF _POING_COMETE EQU $2604 ; POING COMETE
DEF _ULTIMAPOING EQU $2605 ; ULTIMAPOING
DEF _JACKPOT     EQU $2606 ; JACKPOT
DEF _POING_DE_FEU EQU $2607 ; POING DE FEU
DEF _POINGLACE   EQU $2608 ; POINGLACE
DEF _GRIFFE      EQU $260A ; GRIFFE
DEF _FORCE_POIGNE EQU $260B ; FORCE POIGNE
DEF _GUILLOTINE  EQU $260C ; GUILLOTINE
DEF _DANSE_LAMES EQU $260E ; DANSE-LAMES
DEF _CRU_AILE    EQU $2611 ; CRU-AILE
DEF _CYCLONE     EQU $2612 ; CYCLONE
DEF _SOUPLESSE   EQU $2615 ; SOUPLESSE
DEF _FOUET_LIANES EQU $2616 ; FOUET LIANES
DEF _ECRASEMENT  EQU $2617 ; ECRASEMENT
DEF _DOUBLE_PIED EQU $2618 ; DOUBLE PIED
DEF _ULTIMAWASHI EQU $2619 ; ULTIMAWASHI
DEF _PIED_SAUTE  EQU $261A ; PIED SAUTE
DEF _MAWASHI_GERI EQU $261B ; MAWASHI GERI
DEF _KOUD_KORNE  EQU $261E ; KOUD’KORNE
DEF _FURIE       EQU $261F ; FURIE
DEF _EMPAL_KORNE EQU $2620 ; EMPAL’KORNE
DEF _CHARGE      EQU $2621 ; CHARGE
DEF _PLAQUAGE    EQU $2622 ; PLAQUAGE
DEF _LIGOTAGE    EQU $2623 ; LIGOTAGE
DEF _BELIER      EQU $2624 ; BELIER
DEF _DARD_VENIN  EQU $2628 ; DARD-VENIN
DEF _DOUBLE_DARD EQU $2629 ; DOUBLE-DARD
DEF _DARD_NUEE   EQU $262A ; DARD-NUEE
DEF _GROZ_YEUX   EQU $262B ; GROZ’YEUX
DEF _RUGISSEMENT EQU $262D ; RUGISSEMENT
DEF _HURLEMENT   EQU $262E ; HURLEMENT
DEF _ULTRASON    EQU $2630 ; ULTRASON
DEF _ACIDE       EQU $2633 ; ACIDE
DEF _FLAMMECHE   EQU $2634 ; FLAMMECHE
DEF _PISTOLET_A_O EQU $2637 ; PISTOLET A O
DEF _HYDROCANON  EQU $2638 ; HYDROCANON
DEF _SURF        EQU $2639 ; SURF
DEF _LASER_GLACE EQU $263A ; LASER GLACE
DEF _BLIZZARD    EQU $263B ; BLIZZARD
DEF _BULLES_D_O  EQU $263D ; BULLES D’O
DEF _ULTRALASER  EQU $263F ; ULTRALASER
DEF _PICPIC      EQU $2640 ; PICPIC
DEF _BEC_VRILLE  EQU $2641 ; BEC VRILLE
DEF _FRAPPE_ATLAS EQU $2645 ; FRAPPE ATLAS
DEF _MEGA_SANGSUE EQU $2648 ; MEGA-SANGSUE
DEF _VAMPIGRAINE EQU $2649 ; VAMPIGRAINE
DEF _TRANCH_HERBE EQU $264B ; TRANCH’HERBE
DEF _POUDRE_TOXIK EQU $264D ; POUDRE TOXIK
DEF _POUDRE_DODO EQU $264F ; POUDRE DODO
DEF _DANSE_FLEUR EQU $2650 ; DANSE-FLEUR
DEF _DRACO_RAGE  EQU $2652 ; DRACO-RAGE
DEF _DANSEFLAMME EQU $2653 ; DANSEFLAMME
DEF _ECLAIR      EQU $2654 ; ECLAIR
DEF _CAGE_ECLAIR EQU $2656 ; CAGE-ECLAIR
DEF _TOXIK       EQU $265C ; TOXIK
DEF _CHOC_MENTAL EQU $265D ; CHOC MENTAL
DEF _YOGA        EQU $2660 ; YOGA
DEF _VIVE_ATTAQUE EQU $2662 ; VIVE-ATTAQUE
DEF _TELEPORT    EQU $2664 ; TELEPORT
DEF _TENEBRES    EQU $2665 ; TENEBRES
DEF _COPIE       EQU $2666 ; COPIE
DEF _LILLIPUT    EQU $266B ; LILLIPUT
DEF _BOUL_ARMURE EQU $266F ; BOUL’ARMURE
DEF _BOUCLIER    EQU $2670 ; BOUCLIER
DEF _MUR_LUMIERE EQU $2671 ; MUR LUMIERE
DEF _PROTECTION  EQU $2673 ; PROTECTION
DEF _METRONOME   EQU $2676 ; METRONOME
DEF _BOMB_OEUF   EQU $2679 ; BOMB’OEUF
DEF _DETRITUS    EQU $267C ; DETRITUS
DEF _MASSD_OS    EQU $267D ; MASSD’OS
DEF _DEFLAGRATION EQU $267E ; DEFLAGRATION
DEF _CASCADE     EQU $267F ; CASCADE
DEF _COUD_KRANE  EQU $2682 ; COUD’KRANE
DEF _PICANON     EQU $2683 ; PICANON
DEF _AMNESIE     EQU $2685 ; AMNESIE
DEF _E_COQUE     EQU $2687 ; E-COQUE
DEF _PIED_VOLTIGE EQU $2688 ; PIED VOLTIGE
DEF _INTIMIDATION EQU $2689 ; INTIMIDATION
DEF _DEVOREVE    EQU $268A ; DEVOREVE
DEF _GAZ_TOXIK   EQU $268B ; GAZ TOXIK
DEF _PILONNAGE   EQU $268C ; PILONNAGE
DEF _MORPHING    EQU $2690 ; MORPHING
DEF _UPPERCUT    EQU $2692 ; UPPERCUT
DEF _FLASH       EQU $2694 ; FLASH
DEF _TREMPETTE   EQU $2696 ; TREMPETTE
DEF _ACIDARMURE  EQU $2697 ; ACIDARMURE
DEF _EXPLOSION   EQU $2699 ; EXPLOSION
DEF _COMBO_GRIFFE EQU $269A ; COMBO-GRIFFE
DEF _OSMERANG    EQU $269B ; OSMERANG
DEF _REPOS       EQU $269C ; REPOS
DEF _CROC_DE_MORT EQU $269E ; CROC DE MORT
DEF _ADAPTATION  EQU $26A0 ; ADAPTATION
DEF _TRIPLATTAQUE EQU $26A1 ; TRIPLATTAQUE
DEF _CLONAGE     EQU $26A4 ; CLONAGE
DEF _LUTTE       EQU $26A5 ; LUTTE
DEF _TRIPLE_PIED EQU $26A7 ; TRIPLE PIED
DEF _LARCIN      EQU $26A8 ; LARCIN
DEF _MALEDICTION EQU $26AE ; MALEDICTION
DEF _CONVERSION_2 EQU $26B0 ; CONVERSION 2
DEF _SPORE_COTON EQU $26B2 ; SPORE COTON
DEF _ABRI        EQU $26B6 ; ABRI
DEF _MACH_PUNCH  EQU $26B7 ; MACH PUNCH
DEF _FEINTE      EQU $26B9 ; FEINTE
DEF _DOUX_BAISER EQU $26BA ; DOUX BAISER
DEF _COGNOBIDON  EQU $26BB ; COGNOBIDON
DEF _BOMB_BEURK  EQU $26BC ; BOMB-BEURK
DEF _COUD_BOUE   EQU $26BD ; COUD’BOUE
DEF _PICOTS      EQU $26BF ; PICOTS
DEF _ELECANON    EQU $26C0 ; ELECANON
DEF _CLAIRVOYANCE EQU $26C1 ; CLAIRVOYANCE
DEF _PRLVT_DESTIN EQU $26C2 ; PRLVT DESTIN
DEF _REQUIEM     EQU $26C3 ; REQUIEM
DEF _DETECTION   EQU $26C5 ; DETECTION
DEF _CHARGE_OS   EQU $26C6 ; CHARGE-OS
DEF _VERROUILLAGE EQU $26C7 ; VERROUILLAGE
DEF _FAUX_CHAGE  EQU $26CE ; FAUX-CHAGE
DEF _LAIT_A_BOIRE EQU $26D0 ; LAIT A BOIRE
DEF _TAILLADE    EQU $26D2 ; TAILLADE
DEF _AILE_D_ACIER EQU $26D3 ; AILE D’ACIER
DEF _ATTRACTION  EQU $26D5 ; ATTRACTION
DEF _BLABLA_DODO EQU $26D6 ; BLABLA DODO
DEF _CADEAU      EQU $26D9 ; CADEAU
DEF _FRUSTRATION EQU $26DA ; FRUSTRATION
DEF _AMPLEUR     EQU $26DE ; AMPLEUR
DEF _DYNAMOPOING EQU $26DF ; DYNAMOPOING
DEF _MEGACORNE   EQU $26E0 ; MEGACORNE
DEF _DRACOSOUFFLE EQU $26E1 ; DRACOSOUFFLE
DEF _RELAIS      EQU $26E2 ; RELAIS
DEF _GRIFFE_ACIER EQU $26E8 ; GRIFFE ACIER
DEF _RAYON_LUNE  EQU $26EC ; RAYON LUNE
DEF _PUIS__CACHEE EQU $26ED ; PUIS. CACHEE
DEF _OURAGAN     EQU $26EF ; OURAGAN
DEF _ZENITH      EQU $26F1 ; ZENITH
DEF _VOILE_MIROIR EQU $26F3 ; VOILE MIROIR
DEF _PRESCIENCE  EQU $26F8 ; PRESCIENCE
DEF _BASTON      EQU $26FB ; BASTON
DEF _BLUFF       EQU $26FC ; BLUFF
DEF _STOCKAGE    EQU $26FE ; STOCKAGE
DEF _RELACHE     EQU $26FF ; RELACHE
DEF _AVALE       EQU $2700 ; AVALE
DEF _CANICULE    EQU $2701 ; CANICULE
DEF _PROVOC      EQU $270D ; PROVOC
DEF _COUP_D_MAIN EQU $270E ; COUP D’MAIN
DEF _TOURMAGIK   EQU $270F ; TOURMAGIK
DEF _IMITATION   EQU $2710 ; IMITATION
DEF _VOEU        EQU $2711 ; VOEU
DEF _ASSISTANCE  EQU $2712 ; ASSISTANCE
DEF _RACINES     EQU $2713 ; RACINES
DEF _SURPUISSANCE EQU $2714 ; SURPUISSANCE
DEF _REFLET_MAGIK EQU $2715 ; REFLET MAGIK
DEF _RECYCLAGE   EQU $2716 ; RECYCLAGE
DEF _VENDETTA    EQU $2717 ; VENDETTA
DEF _SABOTAGE    EQU $271A ; SABOTAGE
DEF _ERUPTION    EQU $271C ; ERUPTION
DEF _POSSESSIF   EQU $271E ; POSSESSIF
DEF _REGENERATION EQU $271F ; REGENERATION
DEF _SAISIE      EQU $2721 ; SAISIE
DEF _FORCE_CACHEE EQU $2722 ; FORCE CACHEE
DEF _PLONGEE     EQU $2723 ; PLONGEE
DEF _COGNE       EQU $2724 ; COGNE
DEF _CAMOUFLAGE  EQU $2725 ; CAMOUFLAGE
DEF _LUMIQUEUE   EQU $2726 ; LUMIQUEUE
DEF _LUMI_ECLAT  EQU $2727 ; LUMI-ECLAT
DEF _BALL_BRUME  EQU $2728 ; BALL’BRUME
DEF _DANSE_PLUME EQU $2729 ; DANSE-PLUME
DEF _DANSE_FOLLE EQU $272A ; DANSE-FOLLE
DEF _PIED_BRULEUR EQU $272B ; PIED BRULEUR
DEF _LANCE_BOUE  EQU $272C ; LANCE-BOUE
DEF _POING_DARD  EQU $272E ; POING DARD
DEF _PARESSE     EQU $272F ; PARESSE
DEF _MEGAPHONE   EQU $2730 ; MEGAPHONE
DEF _CROCHETVENIN EQU $2731 ; CROCHETVENIN
DEF _ECLATEGRIFFE EQU $2732 ; ECLATEGRIFFE
DEF _OCROUPI     EQU $274A ; OCROUPI
DEF _BALLE_GRAINE EQU $274B ; BALLE GRAINE
DEF _AEROPIQUE   EQU $274C ; AEROPIQUE
DEF _MUR_DE_FER  EQU $274E ; MUR DE FER
DEF _BARRAGE     EQU $274F ; BARRAGE
DEF _GRONDEMENT  EQU $2750 ; GRONDEMENT
DEF _DRACOGRIFFE EQU $2751 ; DRACOGRIFFE
DEF _GONFLETTE   EQU $2753 ; GONFLETTE
DEF _REBOND      EQU $2754 ; REBOND
DEF _TIR_DE_BOUE EQU $2755 ; TIR DE BOUE
DEF _QUEUE_POISON EQU $2756 ; QUEUE-POISON
DEF _IMPLORE     EQU $2757 ; IMPLORE
DEF _FEUILLEMAGIK EQU $2759 ; FEUILLEMAGIK
DEF _TOURNIQUET  EQU $275A ; TOURNIQUET
DEF _PLENITUDE   EQU $275B ; PLENITUDE
DEF _LAME_FEUILLE EQU $275C ; LAME-FEUILLE
DEF _DANSE_DRACO EQU $275D ; DANSE DRACO
DEF _BOULE_ROC   EQU $275E ; BOULE ROC
DEF _ONDE_DE_CHOC EQU $275F ; ONDE DE CHOC
DEF _VIBRAQUA    EQU $2760 ; VIBRAQUA
DEF _RAFALE_FEU  EQU $2761 ; RAFALE FEU
DEF _HYDROBLAST  EQU $2762 ; HYDROBLAST
DEF _STALAGTITE  EQU $2763 ; STALAGTITE
DEF _VEGE_ATTAK  EQU $2764 ; VEGE-ATTAK
DEF _ELECTACLE   EQU $2765 ; ELECTACLE
DEF _CARNAREKET  EQU $2766 ; CARNAREKET
DEF _PSYCHO_BOOST EQU $2767 ; PSYCHO BOOST

; MOTS COOL
DEF CHENAPAN     EQU $2800 ; CHENAPAN
DEF CA_BICHE     EQU $2801 ; CA BICHE
DEF P_TIT_GARS   EQU $2802 ; P’TIT GARS
DEF MES_AIEUX_   EQU $2803 ; MES AIEUX!
DEF C_EST_COTON  EQU $2804 ; C’EST COTON
DEF ANE_BATE     EQU $2805 ; ANE BATE
DEF CA_BOUME_    EQU $2806 ; CA BOUME?
DEF CA_GAZE_     EQU $2807 ; CA GAZE?
DEF JEUNETTE     EQU $2808 ; JEUNETTE
DEF EN_VOGUE     EQU $2809 ; EN VOGUE
DEF _IN          EQU $280A ; IN
DEF HAS_BEEN     EQU $280B ; HAS BEEN
DEF A_LA_PAGE    EQU $280C ; A LA PAGE
DEF CA_ROULE     EQU $280D ; CA ROULE
DEF MALOTRU      EQU $280E ; MALOTRU
DEF GOUGNAFIER   EQU $280F ; GOUGNAFIER
DEF BATH         EQU $2810 ; BATH
DEF SACREBLEU_   EQU $2811 ; SACREBLEU!
DEF SAPRISTI     EQU $2812 ; SAPRISTI
DEF C_EST_BALLOT EQU $2813 ; C’EST BALLOT
DEF TT_TOURS     EQU $2814 ; 33 TOURS
DEF PIGNOUF      EQU $2815 ; PIGNOUF
DEF BAL          EQU $2816 ; BAL
DEF SACRIPANT    EQU $2817 ; SACRIPANT
DEF _OUT         EQU $2818 ; OUT
DEF C_EST_L_PIED EQU $2819 ; C’EST L’PIED
DEF V_LA_TI_PAS  EQU $281A ; V’LA TI PAS
DEF MA_MIE       EQU $281B ; MA MIE
DEF COOL_RAOUL   EQU $281C ; COOL RAOUL
DEF DONZELLE     EQU $281D ; DONZELLE
DEF RELAX__MAX   EQU $281E ; RELAX, MAX
DEF JEUNOT       EQU $281F ; JEUNOT
DEF NAZE         EQU $2820 ; NAZE

; POKéMON2
DEF __BULBIZARRE EQU $2A01 ; BULBIZARRE
DEF __HERBIZARRE EQU $2A02 ; HERBIZARRE
DEF __FLORIZARRE EQU $2A03 ; FLORIZARRE
DEF __SALAMECHE  EQU $2A04 ; SALAMECHE
DEF __REPTINCEL  EQU $2A05 ; REPTINCEL
DEF __DRACAUFEU  EQU $2A06 ; DRACAUFEU
DEF __CARAPUCE   EQU $2A07 ; CARAPUCE
DEF __CARABAFFE  EQU $2A08 ; CARABAFFE
DEF __TORTANK    EQU $2A09 ; TORTANK
DEF __CHENIPAN   EQU $2A0A ; CHENIPAN
DEF __CHRYSACIER EQU $2A0B ; CHRYSACIER
DEF __PAPILUSION EQU $2A0C ; PAPILUSION
DEF __ASPICOT    EQU $2A0D ; ASPICOT
DEF __COCONFORT  EQU $2A0E ; COCONFORT
DEF __DARDARGNAN EQU $2A0F ; DARDARGNAN
DEF __ROUCOOL    EQU $2A10 ; ROUCOOL
DEF __ROUCOUPS   EQU $2A11 ; ROUCOUPS
DEF __ROUCARNAGE EQU $2A12 ; ROUCARNAGE
DEF __RATTATA    EQU $2A13 ; RATTATA
DEF __RATTATAC   EQU $2A14 ; RATTATAC
DEF __PIAFABEC   EQU $2A15 ; PIAFABEC
DEF __RAPASDEPIC EQU $2A16 ; RAPASDEPIC
DEF __ABO        EQU $2A17 ; ABO
DEF __ARBOK      EQU $2A18 ; ARBOK
DEF __PIKACHU    EQU $2A19 ; PIKACHU
DEF __RAICHU     EQU $2A1A ; RAICHU
DEF __SABELETTE  EQU $2A1B ; SABELETTE
DEF __SABLAIREAU EQU $2A1C ; SABLAIREAU
DEF __NIDORAN_F  EQU $2A1D ; NIDORAN♀
DEF __NIDORINA   EQU $2A1E ; NIDORINA
DEF __NIDOQUEEN  EQU $2A1F ; NIDOQUEEN
DEF __NIDORAN_M  EQU $2A20 ; NIDORAN♂
DEF __NIDORINO   EQU $2A21 ; NIDORINO
DEF __NIDOKING   EQU $2A22 ; NIDOKING
DEF __MELOFEE    EQU $2A23 ; MELOFEE
DEF __MELODELFE  EQU $2A24 ; MELODELFE
DEF __GOUPIX     EQU $2A25 ; GOUPIX
DEF __FEUNARD    EQU $2A26 ; FEUNARD
DEF __RONDOUDOU  EQU $2A27 ; RONDOUDOU
DEF __GRODOUDOU  EQU $2A28 ; GRODOUDOU
DEF __NOSFERAPTI EQU $2A29 ; NOSFERAPTI
DEF __NOSFERALTO EQU $2A2A ; NOSFERALTO
DEF __MYSTHERBE  EQU $2A2B ; MYSTHERBE
DEF __ORTIDE     EQU $2A2C ; ORTIDE
DEF __RAFFLESIA  EQU $2A2D ; RAFFLESIA
DEF __PARAS      EQU $2A2E ; PARAS
DEF __PARASECT   EQU $2A2F ; PARASECT
DEF __MIMITOSS   EQU $2A30 ; MIMITOSS
DEF __AEROMITE   EQU $2A31 ; AEROMITE
DEF __TAUPIQUEUR EQU $2A32 ; TAUPIQUEUR
DEF __TRIOPIKEUR EQU $2A33 ; TRIOPIKEUR
DEF __MIAOUSS    EQU $2A34 ; MIAOUSS
DEF __PERSIAN    EQU $2A35 ; PERSIAN
DEF __PSYKOKWAK  EQU $2A36 ; PSYKOKWAK
DEF __AKWAKWAK   EQU $2A37 ; AKWAKWAK
DEF __FEROSINGE  EQU $2A38 ; FEROSINGE
DEF __COLOSSINGE EQU $2A39 ; COLOSSINGE
DEF __CANINOS    EQU $2A3A ; CANINOS
DEF __ARCANIN    EQU $2A3B ; ARCANIN
DEF __PTITARD    EQU $2A3C ; PTITARD
DEF __TETARTE    EQU $2A3D ; TETARTE
DEF __TARTARD    EQU $2A3E ; TARTARD
DEF __ABRA       EQU $2A3F ; ABRA
DEF __KADABRA    EQU $2A40 ; KADABRA
DEF __ALAKAZAM   EQU $2A41 ; ALAKAZAM
DEF __MACHOC     EQU $2A42 ; MACHOC
DEF __MACHOPEUR  EQU $2A43 ; MACHOPEUR
DEF __MACKOGNEUR EQU $2A44 ; MACKOGNEUR
DEF __CHETIFLOR  EQU $2A45 ; CHETIFLOR
DEF __BOUSTIFLOR EQU $2A46 ; BOUSTIFLOR
DEF __EMPIFLOR   EQU $2A47 ; EMPIFLOR
DEF __TENTACOOL  EQU $2A48 ; TENTACOOL
DEF __TENTACRUEL EQU $2A49 ; TENTACRUEL
DEF __RACAILLOU  EQU $2A4A ; RACAILLOU
DEF __GRAVALANCH EQU $2A4B ; GRAVALANCH
DEF __GROLEM     EQU $2A4C ; GROLEM
DEF __PONYTA     EQU $2A4D ; PONYTA
DEF __GALOPA     EQU $2A4E ; GALOPA
DEF __RAMOLOSS   EQU $2A4F ; RAMOLOSS
DEF __FLAGADOSS  EQU $2A50 ; FLAGADOSS
DEF __MAGNETI    EQU $2A51 ; MAGNETI
DEF __MAGNETON   EQU $2A52 ; MAGNETON
DEF __CANARTICHO EQU $2A53 ; CANARTICHO
DEF __DODUO      EQU $2A54 ; DODUO
DEF __DODRIO     EQU $2A55 ; DODRIO
DEF __OTARIA     EQU $2A56 ; OTARIA
DEF __LAMANTINE  EQU $2A57 ; LAMANTINE
DEF __TADMORV    EQU $2A58 ; TADMORV
DEF __GROTADMORV EQU $2A59 ; GROTADMORV
DEF __KOKIYAS    EQU $2A5A ; KOKIYAS
DEF __CRUSTABRI  EQU $2A5B ; CRUSTABRI
DEF __FANTOMINUS EQU $2A5C ; FANTOMINUS
DEF __SPECTRUM   EQU $2A5D ; SPECTRUM
DEF __ECTOPLASMA EQU $2A5E ; ECTOPLASMA
DEF __ONIX       EQU $2A5F ; ONIX
DEF __SOPORIFIK  EQU $2A60 ; SOPORIFIK
DEF __HYPNOMADE  EQU $2A61 ; HYPNOMADE
DEF __KRABBY     EQU $2A62 ; KRABBY
DEF __KRABBOSS   EQU $2A63 ; KRABBOSS
DEF __VOLTORBE   EQU $2A64 ; VOLTORBE
DEF __ELECTRODE  EQU $2A65 ; ELECTRODE
DEF __NOEUNOEUF  EQU $2A66 ; NOEUNOEUF
DEF __NOADKOKO   EQU $2A67 ; NOADKOKO
DEF __OSSELAIT   EQU $2A68 ; OSSELAIT
DEF __OSSATUEUR  EQU $2A69 ; OSSATUEUR
DEF __KICKLEE    EQU $2A6A ; KICKLEE
DEF __TYGNON     EQU $2A6B ; TYGNON
DEF __EXCELANGUE EQU $2A6C ; EXCELANGUE
DEF __SMOGO      EQU $2A6D ; SMOGO
DEF __SMOGOGO    EQU $2A6E ; SMOGOGO
DEF __RHINOCORNE EQU $2A6F ; RHINOCORNE
DEF __RHINOFEROS EQU $2A70 ; RHINOFEROS
DEF __LEVEINARD  EQU $2A71 ; LEVEINARD
DEF __SAQUEDENEU EQU $2A72 ; SAQUEDENEU
DEF __KANGOUREX  EQU $2A73 ; KANGOUREX
DEF __HYPOTREMPE EQU $2A74 ; HYPOTREMPE
DEF __HYPOCEAN   EQU $2A75 ; HYPOCEAN
DEF __POISSIRENE EQU $2A76 ; POISSIRENE
DEF __POISSOROY  EQU $2A77 ; POISSOROY
DEF __STARI      EQU $2A78 ; STARI
DEF __STAROSS    EQU $2A79 ; STAROSS
DEF __M__MIME    EQU $2A7A ; M. MIME
DEF __INSECATEUR EQU $2A7B ; INSECATEUR
DEF __LIPPOUTOU  EQU $2A7C ; LIPPOUTOU
DEF __ELEKTEK    EQU $2A7D ; ELEKTEK
DEF __MAGMAR     EQU $2A7E ; MAGMAR
DEF __SCARABRUTE EQU $2A7F ; SCARABRUTE
DEF __TAUROS     EQU $2A80 ; TAUROS
DEF __MAGICARPE  EQU $2A81 ; MAGICARPE
DEF __LEVIATOR   EQU $2A82 ; LEVIATOR
DEF __LOKHLASS   EQU $2A83 ; LOKHLASS
DEF __METAMORPH  EQU $2A84 ; METAMORPH
DEF __EVOLI      EQU $2A85 ; EVOLI
DEF __AQUALI     EQU $2A86 ; AQUALI
DEF __VOLTALI    EQU $2A87 ; VOLTALI
DEF __PYROLI     EQU $2A88 ; PYROLI
DEF __PORYGON    EQU $2A89 ; PORYGON
DEF __AMONITA    EQU $2A8A ; AMONITA
DEF __AMONISTAR  EQU $2A8B ; AMONISTAR
DEF __KABUTO     EQU $2A8C ; KABUTO
DEF __KABUTOPS   EQU $2A8D ; KABUTOPS
DEF __PTERA      EQU $2A8E ; PTERA
DEF __RONFLEX    EQU $2A8F ; RONFLEX
DEF __ARTIKODIN  EQU $2A90 ; ARTIKODIN
DEF __ELECTHOR   EQU $2A91 ; ELECTHOR
DEF __SULFURA    EQU $2A92 ; SULFURA
DEF __MINIDRACO  EQU $2A93 ; MINIDRACO
DEF __DRACO      EQU $2A94 ; DRACO
DEF __DRACOLOSSE EQU $2A95 ; DRACOLOSSE
DEF __MEWTWO     EQU $2A96 ; MEWTWO
DEF __MEW        EQU $2A97 ; MEW
DEF __GERMIGNON  EQU $2A98 ; GERMIGNON
DEF __MACRONIUM  EQU $2A99 ; MACRONIUM
DEF __MEGANIUM   EQU $2A9A ; MEGANIUM
DEF __HERICENDRE EQU $2A9B ; HERICENDRE
DEF __FEURISSON  EQU $2A9C ; FEURISSON
DEF __TYPHLOSION EQU $2A9D ; TYPHLOSION
DEF __KAIMINUS   EQU $2A9E ; KAIMINUS
DEF __CROCRODIL  EQU $2A9F ; CROCRODIL
DEF __ALIGATUEUR EQU $2AA0 ; ALIGATUEUR
DEF __FOUINETTE  EQU $2AA1 ; FOUINETTE
DEF __FOUINAR    EQU $2AA2 ; FOUINAR
DEF __HOOTHOOT   EQU $2AA3 ; HOOTHOOT
DEF __NOARFANG   EQU $2AA4 ; NOARFANG
DEF __COXY       EQU $2AA5 ; COXY
DEF __COXYCLAQUE EQU $2AA6 ; COXYCLAQUE
DEF __MIMIGAL    EQU $2AA7 ; MIMIGAL
DEF __MIGALOS    EQU $2AA8 ; MIGALOS
DEF __NOSTENFER  EQU $2AA9 ; NOSTENFER
DEF __LOUPIO     EQU $2AAA ; LOUPIO
DEF __LANTURN    EQU $2AAB ; LANTURN
DEF __PICHU      EQU $2AAC ; PICHU
DEF __MELO       EQU $2AAD ; MELO
DEF __TOUDOUDOU  EQU $2AAE ; TOUDOUDOU
DEF __TOGEPI     EQU $2AAF ; TOGEPI
DEF __TOGETIC    EQU $2AB0 ; TOGETIC
DEF __NATU       EQU $2AB1 ; NATU
DEF __XATU       EQU $2AB2 ; XATU
DEF __WATTOUAT   EQU $2AB3 ; WATTOUAT
DEF __LAINERGIE  EQU $2AB4 ; LAINERGIE
DEF __PHARAMP    EQU $2AB5 ; PHARAMP
DEF __JOLIFLOR   EQU $2AB6 ; JOLIFLOR
DEF __MARILL     EQU $2AB7 ; MARILL
DEF __AZUMARILL  EQU $2AB8 ; AZUMARILL
DEF __SIMULARBRE EQU $2AB9 ; SIMULARBRE
DEF __TARPAUD    EQU $2ABA ; TARPAUD
DEF __GRANIVOL   EQU $2ABB ; GRANIVOL
DEF __FLORAVOL   EQU $2ABC ; FLORAVOL
DEF __COTOVOL    EQU $2ABD ; COTOVOL
DEF __CAPUMAIN   EQU $2ABE ; CAPUMAIN
DEF __TOURNEGRIN EQU $2ABF ; TOURNEGRIN
DEF __HELIATRONC EQU $2AC0 ; HELIATRONC
DEF __YANMA      EQU $2AC1 ; YANMA
DEF __AXOLOTO    EQU $2AC2 ; AXOLOTO
DEF __MARAISTE   EQU $2AC3 ; MARAISTE
DEF __MENTALI    EQU $2AC4 ; MENTALI
DEF __NOCTALI    EQU $2AC5 ; NOCTALI
DEF __CORNEBRE   EQU $2AC6 ; CORNEBRE
DEF __ROIGADA    EQU $2AC7 ; ROIGADA
DEF __FEUFOREVE  EQU $2AC8 ; FEUFOREVE
DEF __ZARBI      EQU $2AC9 ; ZARBI
DEF __QULBUTOKE  EQU $2ACA ; QULBUTOKE
DEF __GIRAFARIG  EQU $2ACB ; GIRAFARIG
DEF __POMDEPIK   EQU $2ACC ; POMDEPIK
DEF __FORETRESS  EQU $2ACD ; FORETRESS
DEF __INSOLOURDO EQU $2ACE ; INSOLOURDO
DEF __SCORPLANE  EQU $2ACF ; SCORPLANE
DEF __STEELIX    EQU $2AD0 ; STEELIX
DEF __SNUBBULL   EQU $2AD1 ; SNUBBULL
DEF __GRANBULL   EQU $2AD2 ; GRANBULL
DEF __QWILFISH   EQU $2AD3 ; QWILFISH
DEF __CIZAYOX    EQU $2AD4 ; CIZAYOX
DEF __CARATROC   EQU $2AD5 ; CARATROC
DEF __SCARHINO   EQU $2AD6 ; SCARHINO
DEF __FARFURET   EQU $2AD7 ; FARFURET
DEF __TEDDIURSA  EQU $2AD8 ; TEDDIURSA
DEF __URSARING   EQU $2AD9 ; URSARING
DEF __LIMAGMA    EQU $2ADA ; LIMAGMA
DEF __VOLCAROPOD EQU $2ADB ; VOLCAROPOD
DEF __MARCACRIN  EQU $2ADC ; MARCACRIN
DEF __COCHIGNON  EQU $2ADD ; COCHIGNON
DEF __CORAYON    EQU $2ADE ; CORAYON
DEF __REMORAID   EQU $2ADF ; REMORAID
DEF __OCTILLERY  EQU $2AE0 ; OCTILLERY
DEF __CADOIZO    EQU $2AE1 ; CADOIZO
DEF __DEMANTA    EQU $2AE2 ; DEMANTA
DEF __AIRMURE    EQU $2AE3 ; AIRMURE
DEF __MALOSSE    EQU $2AE4 ; MALOSSE
DEF __DEMOLOSSE  EQU $2AE5 ; DEMOLOSSE
DEF __HYPOROI    EQU $2AE6 ; HYPOROI
DEF __PHANPY     EQU $2AE7 ; PHANPY
DEF __DONPHAN    EQU $2AE8 ; DONPHAN
DEF __PORYGON2   EQU $2AE9 ; PORYGON2
DEF __CERFROUSSE EQU $2AEA ; CERFROUSSE
DEF __QUEULORIOR EQU $2AEB ; QUEULORIOR
DEF __DEBUGANT   EQU $2AEC ; DEBUGANT
DEF __KAPOERA    EQU $2AED ; KAPOERA
DEF __LIPPOUTI   EQU $2AEE ; LIPPOUTI
DEF __ELEKID     EQU $2AEF ; ELEKID
DEF __MAGBY      EQU $2AF0 ; MAGBY
DEF __ECREMEUH   EQU $2AF1 ; ECREMEUH
DEF __LEUPHORIE  EQU $2AF2 ; LEUPHORIE
DEF __RAIKOU     EQU $2AF3 ; RAIKOU
DEF __ENTEI      EQU $2AF4 ; ENTEI
DEF __SUICUNE    EQU $2AF5 ; SUICUNE
DEF __EMBRYLEX   EQU $2AF6 ; EMBRYLEX
DEF __YMPHECT    EQU $2AF7 ; YMPHECT
DEF __TYRANOCIF  EQU $2AF8 ; TYRANOCIF
DEF __LUGIA      EQU $2AF9 ; LUGIA
DEF __HO_OH      EQU $2AFA ; HO-OH
DEF __CELEBI     EQU $2AFB ; CELEBI

