DEF AQUA_LEADER		EQU $00 ; *
DEF SBIRE_AQUA_M	EQU $01 ; TEAM AQUA*
DEF SBIRE_AQUA_F	EQU $02 ; TEAM AQUA*
; no AQUA ADMIN
DEF AROMA		EQU $03
DEF RUINEMANIAC		EQU $04
DEF JOURNALISTES	EQU $05 ; *
DEF FLOTTEUR_F		EQU $06 ; TUBER
DEF FLOTTEUR_M		EQU $07 ; TUBER
DEF TOPDRESSEUR_M	EQU $08 ; COOLTRAINER♂
DEF TOPDRESSEUR_F	EQU $09 ; COOLTRAINER♀
DEF MYSTIMANIAC		EQU $0A
DEF MADEMOISELLE	EQU $0B
DEF CANON		EQU $0C
DEF RICHARD		EQU $0D
DEF POKEMANIAC		EQU $0E ; POKéMANIAC
DEF NAGEUR_M		EQU $0F ; SWIMMER♂
DEF KARATEKA		EQU $10 ; item name
DEF GUITARISTE		EQU $11
DEF SALTIMBANQUE	EQU $12
DEF CAMPEUR		EQU $13
DEF ENTOMOMANIAC	EQU $14
DEF KINESISTE_M		EQU $15 ; PSYCHIC
DEF KINESISTE_F		EQU $16 ; PSYCHIC
DEF GENTLEMAN		EQU $17
DEF CONSEIL_4_SIDNEY	EQU $18 ; ELITE FOUR*
DEF CONSEIL_4_PHOEBE	EQU $19 ; ELITE FOUR*
DEF CHAMPION_ROXANNE	EQU $1A ; LEADER*
DEF CHAMPION_BASTIEN	EQU $1B ; LEADER*
DEF CHAMPION_TATE_LIZA	EQU $1C ; LEADER*
DEF ELEVE_M		EQU $1D ; SCHOOL KID
DEF ELEVE_F		EQU $1E ; SCHOOL KID
DEF SR_AND_JR    	EQU $1F ; SR. AND JR.*
; no WINSTRATE
DEF POKEFAN_M		EQU $20 ; POKéFAN
DEF POKEFAN_F		EQU $21 ; POKéFAN
DEF EXPERT_M		EQU $22 ; EXPERT
DEF EXPERT_F		EQU $23 ; EXPERT
DEF GAMIN		EQU $24
DEF CHAMPION		EQU $25 ; *
DEF PECHEUR		EQU $26
DEF TRIATHLETE_M_VELO	EQU $27 ; TRIATHLETE
DEF TRIATHLETE_F_VELO	EQU $28 ; TRIATHLETE
DEF TRIATHLETE_M_COURSE	EQU $29 ; TRIATHLETE
DEF TRIATHLETE_F_COURSE	EQU $2A ; TRIATHLETE
DEF TRIATHLETE_M_NAGE	EQU $2B ; TRIATHLETE
DEF TRIATHLETE_F_NAGE	EQU $2C ; TRIATHLETE
DEF DRACOLOGUE		EQU $2D
DEF ORNITHOLOGUE	EQU $2E
DEF NINJA_FAN		EQU $2F
DEF COMBATTANTE		EQU $30
DEF SOEUR_PARASOL	EQU $31
DEF NAGEUR_F		EQU $32 ; SWIMMER♀
DEF PIQUE_NIQUE		EQU $33
DEF JUMELLES		EQU $34 ; *
DEF MARIN		EQU $35
DEF BOARDER_1		EQU $36 ; *
DEF BOARDER_2		EQU $37 ; *
DEF COLLEC		EQU $38
DEF DRESSEUR_PKMN_TIMMY	EQU $39 ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_1	EQU $3A ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_2	EQU $3B ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_3	EQU $3C ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_1	EQU $3D ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_2	EQU $3E ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_3	EQU $3F ; \{PKMN} TRAINER*
DEF ELEVEUR_PKMN_M	EQU $40 ; \{PKMN} BREEDER
DEF ELEVEUR_PKMN_F	EQU $41 ; \{PKMN} BREEDER
DEF PKMN_RANGER_M	EQU $42 ; \{PKMN} RANGER
DEF PKMN_RANGER_F	EQU $43 ; \{PKMN} RANGER
DEF MAGMA_LEADER	EQU $44 ; *
DEF SBIRE_MAGMA_M	EQU $45 ; *
DEF SBIRE_MAGMA_F	EQU $46 ; *
; no MAGMA ADMIN
DEF FILLETTE		EQU $47
DEF SCOUT		EQU $48
DEF MONTAGNARD		EQU $49
DEF JEUNE_COUPLE	EQU $4A ; *
DEF VIEUX_COUPLE	EQU $4B ; *
DEF FRERE_ET_SOEUR	EQU $4C ; *
; $4D: BLACK BELT with a Lass sprite
; $4E: PKMN TRAINER with a Youngster sprite
; $4F: GUITARIST with a Youngster sprite
; $8F: GENTLEMAN with a PKMN Breeder sprite
; $FB: TWINS with May’s sprite
; $FC: PKMN TRAINER with a Pokéfan (♂) sprite
; $FD: SAILOR with May’s sprite
; $FE: PKMN TRAINER with a Sis and Bro sprite
; $FF: BOARDER with May’s sprite
